### ISSUE TITLE
How do I use Cachix with a remote builder and nixops?

### ISSUE THREAD

**Issue by jezen** [cachix/cachix#100]
I am developing on MacOS, and building for NixOps/AWS deployments with a NixOS Docker machine, as described [here](https://medium.com/@zw3rk/provisioning-a-nixos-server-from-macos-d36055afc4ad).

How do I push those Linux-built packages to Cachix?

**Comment by domenkozar** [comment]
@jezen pushing whole machines is tricky since you're also pushing potentially passwords, etc. Are those for experiments?

You can pass `--build-only` to nixops and the last path to build should be the one that contains all closures of the machines, pipe that one to cachix.

**Comment by jezen** [comment]
@domenkozar I think it's not the machine that I want to push to Cachix, but instead I want to push all the project's Haskell dependencies (like GHC) which take a long time to build.

**Comment by jezen** [comment]
@domenkozar After thinking about this some more, I feel I should clarify that the paths I want to push to Cachix are not the ones in my host machine's (MacOS) nix store, but the ones in the remote build machine's (NixOS on Docker) nix store.

**Comment by jezen** [comment]
Ok, I figured this out. It turns out I can do the same trick as described [here](https://github.com/cachix/cachix/issues/52).

I created a file like this:

```
# ./packages-for-cachix.nix
let
  # This contains a pinned nixpkgs
  nixpkgs = import ./nixpkgs.nix;

  pkgs = import nixpkgs { localSystem.system = "x86_64-linux"; };

  # This contains the output of `stack2nix --test . > haskell-packages.nix`
  stackage = import ./haskell-packages.nix { pkgs = pkgs; };

  haskellPackages = stackage.override {
    overrides = haskellPackagesNew: haskellPackagesOld: rec {
      esqueleto = pkgs.haskell.lib.dontCheck haskellPackagesOld.esqueleto;
    };
  };

  comparestack = pkgs.haskell.lib.overrideCabal haskellPackages.comparestack (drv: {
    doCheck = false;
    doHaddock = false;
    enableLibraryProfiling = false;
    enableSeparateDataOutput = false;
    enableSharedExecutables = false;
    isLibrary = false;
    postFixup = "rm -rf $out/lib $out/nix-support $out/share/doc";
    testHaskellDepends = [];
  });
in
  comparestack
```

My pinned nixpkgs is here:

```
# ./nixpkgs.nix
(import <nixpkgs> {}).fetchFromGitHub {
  owner = "NixOS";
  repo = "nixpkgs";
  rev = "7283740218a5178185a8c1bf0ecfa861f5f9f0f7";
  sha256 = "1rch0whlswwqfj4z9ijwc0hj9xrbwc04zzgrd4y52fw87s4r4zz5";
}
```
To push my Haskell dependencies to Cachix, I ran:

```
nix-store -qR --include-outputs $(nix-instantiate packages-for-cachix.nix) | cachix push <name>
```

**Comment by domenkozar** [comment]
Glad you solved it :)
