### ISSUE TITLE
error: unknown flag '--substituters'

### ISSUE THREAD

**Issue by lukego** [cachix/cachix#109]
I'm trying to install cachix with Nix 1.11.2 and I'm seeing this error when following the README:

```
[luke@interlaken:~]$ nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
downloading ‘https://github.com/cachix/cachix/tarball/master’... [0/0 KiB, 0.0 KiB/s]
unpacking ‘https://github.com/cachix/cachix/tarball/master’...
error: unknown flag ‘--substituters’
Try ‘nix-env --help’ for more information.

[luke@interlaken:~]$ nix-env --version
nix-env (Nix) 1.11.2
```

Tips?

**Comment by domenkozar** [comment]
Need to change Readme to suggest stable version: `nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/db557aab7b690f5e0e3348459f2e4dc8fd0d9298`

**Comment by domenkozar** [comment]
@lukego ah, you're probably looking for Nix 1.0 support.

```
nix-env -if https://github.com/cachix/cachix/tarball/master
```

Unfortunately you'll have to compile it yourself until it reaches nixpkgs. I'll try to make a release today.

**Comment by domenkozar** [comment]
Please reopen if you get another error :)
