### ISSUE TITLE
Improve order of looking up existing narinfo

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#116]
As per @roberth,

> you should do a breadth first search from the inputStorePaths

https://github.com/cachix/cachix/blob/7dad39d28a0b79424233f909bac5aee23adfdc29/cachix/src/Cachix/Client/Commands.hs#L178

Note: there should still be a flag to sync whole derivation, because nothing guarantees for someone to push a dependency to cachix without first including it's parents.

**Comment by domenkozar** [comment]
We should probably just implement "mass querying" using one HTTP request.

**Comment by roberth** [comment]
This particular code has been replaced by a native Nix invocation on master, same for the bulk query.
