### ISSUE TITLE
Is cachix.org down?

### ISSUE THREAD

**Issue by philderbeast** [cachix/cachix#117]
I'm trying to compile the [vector](https://github.com/tweag/rules_haskell_examples/tree/master/vector) package using bazel but his is taking a while.

```
> bazel build //vector:vector
INFO: SHA256 (https://github.com/bazelbuild/bazel-skylib/archive/0.2.0.tar.gz) =
 981624731d7371061ca56d532fa00d33bdda3e9d62e085698880346a01d0a6ef
INFO: SHA256 (https://github.com/NixOS/nixpkgs/archive/18.03.tar.gz) =
 954724605f72b9800207f28dd247b04a4b7cc5c923f33e38426f0a4ba60d6444
warning: unable to download 'https://flare-timing.cachix.org/nix-cache-info':
Timeout was reached (28); retrying in 350 ms
warning: unable to download 'https://flare-timing.cachix.org/nix-cache-info':
Timeout was reached (28); retrying in 699 ms
warning: unable to download 'https://flare-timing.cachix.org/nix-cache-info':
Timeout was reached (28); retrying in 1126 ms
warning: unable to download 'https://flare-timing.cachix.org/nix-cache-info':
Timeout was reached (28); retrying in 2203 ms
Analyzing: target //vector:vector (10 packages loaded)
```

Is cachix.org down? I'd signed up a few days ago but not yet done anything more with it than follow the registration instructions.

**Comment by philderbeast** [comment]
When browsing to https://cachix.org, I see;

```
Error 502 Ray ID: 44e70ae38cc391e8 • 2018-08-22 17:26:06 UTC
Bad gateway
```

**Comment by dtzWill** [comment]
I'm seeing errors pushing to cachix saying "Origin Connection Time-Out" and given the timing seems likely same issue and that they're changing something or having some problem.  But it's not just you! :)

**Comment by philderbeast** [comment]
Good to know thanks @dtzWill.

**Comment by madnight** [comment]
same problem over here, i try to contact the author via irc

**Comment by chessai** [comment]
Yeah, I just noticed this as well. I contacted @domenkozar on twitter

**Comment by chessai** [comment]
you can temporarily run nix-build with `--option substituters "urls"`, where `urls` is whatever is currently in your substituters in nix.conf minus any cachix urls

**Comment by domenkozar** [comment]
Hey all, it seems like networking was down for 2 hours, I'll do an investigation and report back tomorrow. All good now?

**Comment by philderbeast** [comment]
Good here.

**Comment by chessai** [comment]
Good here as well.

**Comment by PierreR** [comment]
This network issue has been a realization that my system configuration is weak. I could not even do any `nix-build` on my development box.

Here is a link to the configuration : https://github.com/CIRB/devbox/blob/master/system/configuration.nix#L31-L40

What should I do to make the system more resilient in case cachix is down ?

**Comment by chessai** [comment]
@PierreR, I think it's a bug in nix, which is supposed to move on from substituters it cant reach.

**Comment by domenkozar** [comment]
It was down again for last 15minutes, I'll still trying to get the root of the cause, but getting closer. Seems to be some sort of space leak, eating up all memory.

**Comment by domenkozar** [comment]
https://domenkozar.com/2018/09/04/recent-cachix-downtime/

**Comment by bbarker** [comment]
Possibly related, seems to be down again. Not opening a new issue for it though: https://cachix.org/api/v1/login reports 502 (bad gateway) for last few minutes while trying.

**Comment by bbarker** [comment]
@domenkozar briefly looked at your blog on this issue. Interesting stuff i should circle back to. Wondering if  you've thought of using bpftrace for Haskell. Might be too low level to be super useful, not sure. Appears to be supported on NixOS.

**Comment by domenkozar** [comment]
Thanks @bbarker - this time I was running a migration script written in Haskell and it ate all memory. Will set up a bit more sophisticated setup to make sure http can't be bothered. Should be back up now.
