### ISSUE TITLE
narinfo corrupt?

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#120]
Path in question: https://allvm.cachix.org/rcdwq1bsh5lwbvcm6x01fxx5nph90nc6.narinfo

For example:

```
$  nix path-info --json /nix/store/rcdwq1bsh5lwbvcm6x01fxx5nph90nc6-source --store https://allvm.cachix.org
error: NAR info file 'rcdwq1bsh5lwbvcm6x01fxx5nph90nc6.narinfo' is corrupt
```

The path is apparently a git clone of my [NUR repo](https://github.com/dtzWill/nur-packages) FWIW.

Which is problematic for a few reasons:

* How does a corrupt narinfo get created/uploaded? Should this be checked server-side?
* How can I fix this? Did I cause it? I had to disable use of the cache when that path is involved since nix aborts everything when it finds an invalid narinfo, understandably :).

Thanks!

**Comment by domenkozar** [comment]
Looking into it.

**Comment by domenkozar** [comment]
@dtzWill do you have this store path around? Can you run `nix-store --dump /nix/store/rcdwq1bsh5lwbvcm6x01fxx5nph90nc6-source|wc -c`

**Comment by domenkozar** [comment]
> How does a corrupt narinfo get created/uploaded?

Signature is calculated and verified. Maybe Nix doesn't accept files that have narSize of 0. Let's first verify that uploaded file is the right one.

**Comment by domenkozar** [comment]
For reference I'll post narinfo here:

```
StorePath: /nix/store/rcdwq1bsh5lwbvcm6x01fxx5nph90nc6-source
URL: nar/0040f94d11d0039505328a90b2ff48968db873e9e7967307631bf40ef5679275.nar.xz
Compression: xz
FileHash: sha256:0040f94d11d0039505328a90b2ff48968db873e9e7967307631bf40ef5679275
FileSize: 32
NarHash: sha256:0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73
NarSize: 0
Deriver: unknown-deriver
Sig: allvm.cachix.org-1:qtW0r7Fnq5uYmN7IziKk6tbrsLL+zaUFlaB46O/j7c3Q8329zgPuzN8DMPPlz3C5olOnw1oGjxdbBFw93Xk5BQ==
```

**Comment by domenkozar** [comment]
@dtzWill you're probably right, a few exit codes are not checked atm: https://github.com/cachix/cachix/blob/93e559ee98489c39dc2738b749080149c7bc21ed/cachix/src/Cachix/Client/Commands.hs#L238

**Comment by domenkozar** [comment]
Deleted all 19 narinfos with 0 narSize.

**Comment by domenkozar** [comment]
Cachix will now check narSize (once released) and server side also now errors out. What's missing here is proper exit code handling.
