### ISSUE TITLE
cachix push --watch-store doesn't work on macOS

### ISSUE THREAD

**Issue by mightybyte** [cachix/cachix#122]
I haven't directly verified this with the `cachix push` command itself because that's more involved, but I used fsnotify the same way you did to watch and react to nix store modifications and it didn't work.  I tried quite a few different combinations of ways of using the library, and none of them worked, so I'm hypothesizing that it's broken for you as well.

**Comment by domenkozar** [comment]
I'll have access to macos machine on 11th September and will reproduce then.

**Comment by domenkozar** [comment]
@mightybyte https://travis-ci.com/cachix/cachix/jobs/147842771 proves that it does work at least on travis. Could be an issue with some settings or just macOS verison?

**Comment by domenkozar** [comment]
@mightybyte if you have a few minutes ping me and I'll be gladly to help here and come to the bottom of this.
