### ISSUE TITLE
[Help request] Minimize the size of the nar files

### ISSUE THREAD

**Issue by PierreR** [cachix/cachix#125]
I would like to push a build of `taffybar-3.0.0` compiled with `ghc-8.2.2` into cachix (the current version in nixpkgs unstable is built with ghc-8.4 and is broken).

I am just a bit worried about the size of the closure which is about 4G (`nix copy --to`).

Is there a way to minimize the size of what is going to be pushed to a cachix cache ?

Here is a link to the relevant commit: https://github.com/taffybar/taffybar/pull/415

Thanks for your help.

**Comment by domenkozar** [comment]
You can use `justStaticExecutables` combinator if you'd like to only get binaries.

**Comment by PierreR** [comment]
In this particular case the haskell configuration is loaded dynamically by `dyre` . The wrapper is doing`--set NIX_GHC "${ghcWithTaffybar}/bin/ghc"`. 
In this particular case, I guess using `justStaticExecutables` won't help ?

**Comment by PierreR** [comment]
Thanks for your feedback
