### ISSUE TITLE
Use extra-substituters instead of substituters

### ISSUE THREAD

**Issue by pjones** [cachix/cachix#139]
Cachix inserted itself in the `substituters` key inside `/etc/nix/nix.conf`.  This prevents `nixos-rebuild` and other builds from using the default binary cache.

Instead, cachix should use the `extra-substituters` key.

**Comment by domenkozar** [comment]
It should also set https://cache.nixos.org - but this was broken before 0.1.2 :)

**Comment by domenkozar** [comment]
I don't think we should change it now, it would be too much code keeping legacy configuration files sane.

But gist of your issue should have been fixed by giving the correct instructions.

**Comment by pjones** [comment]
I agree.  This is mostly my fault.  I added the configuration that cachix recommended to a custom NixOS module and didn't expect it to affect the system default.  That was a bit stupid.
