### ISSUE TITLE
How can users donate to this project?

### ISSUE THREAD

**Issue by chessai** [cachix/cachix#144]
I imagine this is pretty expensive to maintain. Is it possible to donate?

**Comment by domenkozar** [comment]
Hi @chessai,

I plan to make cachix sustainable by offering authenticated binary caches a paid feature. I do not accept donations, but a paid plan will provide also additional features and be the way to support development.

I hope this answers your question :)

**Comment by chessai** [comment]
@domenkozar thanks!
