### ISSUE TITLE
Modify `~/.config/nix/nix.conf` for trusted users?

### ISSUE THREAD

**Issue by michaelpj** [cachix/cachix#145]
If you're a trusted user it might be nicer to modify the user-local config file. This would also have a better workflow on NixOS without needing to do the things suggested by https://github.com/cachix/cachix/issues/91.

**Comment by domenkozar** [comment]
What version of Nix are you using? That should already be the case unless your Nix version is too old: https://github.com/cachix/cachix/blob/master/cachix/src/Cachix/Client/InstallationMode.hs#L49

**Comment by domenkozar** [comment]
It should have warned you that groups are not supported yet, did you get the warning?

**Comment by michaelpj** [comment]
Yes, but I thought it related to the content of the snippet, which also said to add myself as a trusted user (which I obviously don't need to). So I didn't realise it also affected whether it edited the local config.

Anyway, sounds like this is just another instance of the groups issue.
