### ISSUE TITLE
`cachix use` complains about /etc/nix if it doesn't exist

### ISSUE THREAD

**Issue by colemickens** [cachix/cachix#148]
I'm testing out some stuff with Nix on Ubuntu and noticed this:

```
$ sudo apt update; sudo apt install -qy curl
$ sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
$ curl https://nixos.org/nix/install | sh
$ source /home/test/.nix-profile/etc/profile.d/nix.sh
$ nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
$ cachix use nixpkgs-wayland
Configured https://nixpkgs-wayland.cachix.org binary cache in /home/test/.config/nix/nix.conf
Warning: Couldn't create /etc/nix :/etc/nix: createDirectory: permission denied (Permission denied)Warning: Couldn't create /etc/nix :/etc/nix: createDirectory: permission denied (Permission denied)t
```

I guess I hadn't realized that it seemed to have succeeded, it seemed quite upset about not being able to create/modify `/etc/nix` stuff.

**Comment by domenkozar** [comment]
I agree, something that needs at the very least a clear message of intent.

**Comment by ariutta** [comment]
Is Cachix intended to be used with multi-user Nix installations on non-NixOS systems?

**Comment by ariutta** [comment]
Related: #56

**Comment by domenkozar** [comment]
@ariutta yes, do you have an issue?

**Comment by ariutta** [comment]
I had the same issue described here and thought maybe it's because I was using Nix on Ubuntu, not NixOS. But it sounds as if this issue is fixed now, thanks!
