### ISSUE TITLE
Upstream binary cache

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#16]
There is a common use case why a binary cache would declare other caches as upstream: It expects binaries to come from another binary cache: it is true for all cachix binary caches to depend on official cache.nixos.org

Possible solutions:

a) "Proxy": if there is no such narinfo in current cache, query upstream caches and redirect. Possible issue here is how Nix handles signatures to match the binary cache declared, but I think it could work.

b) "Resign": currently not possible as signing key is not available to cachix and I'd prefer not to support such option.

Brought up by @zimbatm in https://github.com/cachix/cachix/pull/15#discussion_r191387989

**Comment by Zimmi48** [comment]
Indeed, I'd be glad if I could avoid re-pushing to my personal cachix everything that is already in https://cache.nixos.org.

**Comment by dtzWill** [comment]
For cachix devs/provider a similar issue/idea would be to dedup across cachix's in a manner similar to what `nix-store --optimize` does.  I suppose there's also the question of whether this would be undesirable, same for when using an upstream, since the redundancy might in some cases be desired/intentional.

**Comment by asymmetric** [comment]
>  I suppose there's also the question of whether this would be undesirable, same for when using an upstream, since the redundancy might in some cases be desired/intentional.

This could be a local setting.

**Comment by chris-martin** [comment]
I think I'd be utilizing cachix a lot more if we had this feature. I'd like to build NixOS on my desktop, push to cachix, then build on my laptop, so that the laptop doesn't have to rebuild any of my non-standard packages. But in practice right now this doesn't actually save me any time, because it takes me quite a while (I don't know, maybe an hour?) to push my NixOS build to cachix -- which is silly because most of what I'm pushing is already in the upstream cache.

**Comment by domenkozar** [comment]
I wouldn't recommend pushing laptop paths that include also passwords and such to a public cache. Although it's obscured by someone needing to know the hash, if you post it somewhere by accident, they could get your `/etc/passwd` for example.

About the upstream binary cache: I think this would be set as a property to a binary cache where by default it would be cache.nixos.org, but one could remove it or specify additional ones.

**Comment by chris-martin** [comment]
I've set my user passwords with `passwd` and don't have any secrets in the NixOS configuration. So that shouldn't be a concern, right?

**Comment by domenkozar** [comment]
Some Nix modules store secrets in Nix store, it depends on per use case. It's generally bad practice, but you do find it in the wild.

**Comment by risicle** [comment]
Something as simple as a `cachix push mycache --exclude-present-in https://cache.nixos.org` option would do the job for me. This seriously restricts the usefulness of cachix for me and I'm sure fills your server with duplicates.

**Comment by domenkozar** [comment]
Going to implement this in a few weeks.

**Comment by lf-** [comment]
Hi @domenkozar what's the status on this feature right now? Is there a viable workaround? I have a /pile/ of build time dependencies that I really would like to avoid forcing anyone else to build as it takes over an hour to build all of them. This is also going to become a CI problem to compile so much Haskell that's not mine ;-)

**Comment by domenkozar** [comment]
I'm currently working on https://docs.cachix.org/ to cover different CI integrations and general information people are missing right now, and after that it's this issue. 

There is no workaround really at the moment. The overhead of pushing to Cachix shouldn't be that much, are you recompiling dependencies often? Once they are pushed once, they should just stay there.

**Comment by domenkozar** [comment]
Starting the work on this today.

**Comment by domenkozar** [comment]
https://blog.cachix.org/posts/2020-07-28-upstream-caches-avoiding-pushing-paths-in-cache-nixos-org/

**Comment by adrian-gierakowski** [comment]
> https://blog.cachix.org/posts/2020-07-28-upstream-caches-avoiding-pushing-paths-in-cache-nixos-org/

Sounds amazing. Is this implemented on client side?

**Comment by domenkozar** [comment]
No. Implementing it on server side has quite a few advantages:

- global cache of known entries
- enforced for the whole cache
- quite likely faster as it holds open connection all the time
