### ISSUE TITLE
can't run nix-channel --update when cachix is down

### ISSUE THREAD

**Issue by bbigras** [cachix/cachix#165]
I can't seem to be able to update my channels even if removed the nix stuff from configuration.nix.

Any way around that?

```
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

$ sudo nix-channel --update nixos
unpacking channels...
warning: unable to download 'https://nixpkgs-wayland.cachix.org/ad9zys892d2hq588dis8w69fi9dckf1n.narinfo': Timeout was reached (28); retrying in 310 ms
warning: unable to download 'https://nixpkgs-wayland.cachix.org/ad9zys892d2hq588dis8w69fi9dckf1n.narinfo': Timeout was reached (28); retrying in 659 ms
```

**Comment by LightAndLight** [comment]
I have the same issue.

**Comment by domenkozar** [comment]
I've opened upstream issue at https://github.com/NixOS/nix/issues/2661

Workaround would be to comment out substituters in ~/.config/nix/nix.conf temporarily.

**Comment by bbigras** [comment]
> Workaround would be to comment out substituters in ~/.config/nix/nix.conf temporarily.

One weird thing is that I'm pretty sure I didn't have the `~/.config/nix/nix.conf` file. I guess it must be related to me using the [nixpkgs-wayland](https://github.com/colemickens/nixpkgs-wayland) overlay in configuration.nix.

**Comment by domenkozar** [comment]
Yes, on NixOS uncomment nix.binaryCaches.
