### ISSUE TITLE
Remind to run nixos-rebuild in use command

### ISSUE THREAD

**Issue by jorge-jbs** [cachix/cachix#166]
I am a new user of this program (and recent user of NixOS) and after calling `cachix use ...` I copy pasted the output to configuration.nix but forgot to run `nixos-rebuild`. I spent quite a lot of time figuring why it wasn't working. I think it would be a nice UX improvement to remind to run `nixos-rebuild` after adding the lines, just like people in the debian world remind to run `apt update` before install even though it is common knowledge.

**Comment by domenkozar** [comment]
Thanks @jorge-jbs, I'll add this as part of #158 and #160
