### ISSUE TITLE
Overlays integration

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#17]
Add seamless integration for [nixpkgs overlays](https://nixos.org/nixpkgs/manual/#chap-overlays).

It would allow users of a Nix project to say like:

```
cachix overlay add github://domenkozar/foo
```

Which would essentially do a `git clone ...` and `cachix use foo` as per #5

**Comment by srghma** [comment]
What is this issue for? (I just have some problem, maybe its related)

**Comment by domenkozar** [comment]
@srghma I've added a description, I hope motivation is clearer now.

**Comment by domenkozar** [comment]
This has been superseeded by https://github.com/NixOS/rfcs/pull/49 and will be part of #14
