### ISSUE TITLE
Cleanly shut down `cachix push --watch`

### ISSUE THREAD

**Issue by nomeata** [cachix/cachix#183]
I am playing around with using `cachix push --watch` on travis, and it is very convenient. But it seems I tend to lose caching of the final artifact, because travis kills the `cachix push` process before it is done uploading.

It would be nice if there was a `cachix push --unwatch` command that would tell the watching daemon to finish uploading and terminate, and this command would return only when the daemon is done.

**Comment by domenkozar** [comment]
Duplicates #53 - I agree, if you have a suggestion how to implement signaling I'm all ears :)
