### ISSUE TITLE
Provide a static build?

### ISSUE THREAD

**Issue by nomeata** [cachix/cachix#184]
Each of my travis builds now starts with
```
$ nix-env -iA cachix -f https://cachix.org/api/v1/install
unpacking 'https://cachix.org/api/v1/install'...
installing 'cachix-0.2.0'
these paths will be fetched (9.79 MiB download, 46.36 MiB unpacked):
  /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27
  /nix/store/7mrq5v4nnqfkv1ka7a0kdw9mzvqs5w3c-gmp-6.1.2
  /nix/store/bnbq85lsbds5asi8vzjqhvrgq3l9ila8-cachix-0.2.0
  /nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib
  /nix/store/iiymx8j7nlar3gc23lfkcscvr61fng8s-zlib-1.2.11
  /nix/store/k0y9nrym785l61pjw0lp0qk90v2nbpqs-ncurses-6.1-20190112
  /nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1
  /nix/store/mibh7947iwgf5yiqc7njn0igfzlxzdf1-xz-5.2.4
  /nix/store/y1ck4skkvmcnar0y0i1kkmvv0lasvy5b-cachix-0.2.0-data
copying path '/nix/store/y1ck4skkvmcnar0y0i1kkmvv0lasvy5b-cachix-0.2.0-data' from 'https://cache.nixos.org'...
copying path '/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27' from 'https://cache.nixos.org'...
copying path '/nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/7mrq5v4nnqfkv1ka7a0kdw9mzvqs5w3c-gmp-6.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/k0y9nrym785l61pjw0lp0qk90v2nbpqs-ncurses-6.1-20190112' from 'https://cache.nixos.org'...
copying path '/nix/store/mibh7947iwgf5yiqc7njn0igfzlxzdf1-xz-5.2.4' from 'https://cache.nixos.org'...
copying path '/nix/store/iiymx8j7nlar3gc23lfkcscvr61fng8s-zlib-1.2.11' from 'https://cache.nixos.org'...
copying path '/nix/store/bnbq85lsbds5asi8vzjqhvrgq3l9ila8-cachix-0.2.0' from 'https://cache.nixos.org'...
building '/nix/store/rrdzli02y27g1y4ld8ckgsk3f66yrvay-user-environment.drv'...
created 19 symlinks in user environment
The command "nix-env -iA cachix -f https://cachix.org/api/v1/install" exited with 0.
```
ok, it is only 15 seconds, but still: Have you considered building `cachix` statically, maybe with `musl`, i.e. `crossSystem = localLib.systems.examples.musl64`, so that this step has to download only one self-contained and hopefully smaller store path?

**Comment by nomeata** [comment]
Also, I noticed that `https://cachix.org/api/v1/install` is actually a full copy of nixpkgs, and rather large. Is there a way to condense it to only the (evaluated) `.drv` for cachix? Maybe including its dependencies?

**Comment by nomeata** [comment]
Ok, I tried to build `-A pkgsCross.musl64.cachix` to see how large the resulting binary would be, but it seems that the `clock` library cannot be cross-compiled with the version of nixpkgs provided by https://cachix.org/api/v1/install:

```
building
Preprocessing library for clock-0.7.2..
Clock.hsc:44:0: warning: "hsc_alignment" redefined
In file included from dist/build/System/Clock_hsc_test0.c:1:0:
/nix/store/hi40s6cxmnl0gkns9bc57x3cfy9kwgpd-x86_64-unknown-linux-musl-ghc-8.6.3/lib/x86_64-unknown-linux-musl-ghc-8.6.3/template-hsc.h:91:0: note: this is the location of the previous definition
 #define hsc_alignment(x...)                                           \

System/Clock.hsc:44 directive let cannot be handled in cross-compilation mode
builder for '/nix/store/zijb5zl0pvdlvsrp7prb123fx379wq4j-clock-0.7.2-x86_64-unknown-linux-musl.drv' failed with exit code 1
building '/nix/store/a55b9midzh4mlb31zq1b0jcy4lacsl4q-blaze-html-0.9.1.1-x86_64-unknown-linux-musl.drv'...
cannot build derivation '/nix/store/2bajff12p4qwq4zm6lyn15x0hdx3p6pn-hspec-core-2.6.1-x86_64-unknown-linux-musl.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nz1x2sai1zc9mc8ayvnfn744kvyc7g4w-hspec-2.6.1-x86_64-unknown-linux-musl.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/j8wpml46c8s1g0arakg0943w1fym4gba-servant-swagger-1.1.7-x86_64-unknown-linux-musl.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x5vwab0hpnq84h84kjmk45z1fmbi9yn6-cachix-api-0.2.0-x86_64-unknown-linux-musl.drv': 1 dependencies couldn't be built
building '/nix/store/w1jxsp4xqshd08gm4pa6bmvg1b8bq55x-colour-2.3.4-x86_64-unknown-linux-musl.drv'...
cannot build derivation '/nix/store/b9cbgbp14dr1rmr33yxqbnfh2r704fbw-cachix-0.2.0-x86_64-unknown-linux-musl.drv': 1 dependencies couldn't be built
error: build of '/nix/store/b9cbgbp14dr1rmr33yxqbnfh2r704fbw-cachix-0.2.0-x86_64-unknown-linux-musl.drv' failed
```

**Comment by nomeata** [comment]
Adding this patch makes progress here: https://raw.githubusercontent.com/input-output-hk/iohk-nix/master/patches/clock-0.7.2.patch

**Comment by nomeata** [comment]
Oh man, `cachix` has many Haskell package dependencies. A lot of them build fine using `-A pkgsCross.musl64.cachix`, but some fail like this:
```
building '/nix/store/0qpmxlr0fm4bsvsj25bhm0m2j0ma139m-th-orphans-0.13.6-x86_64-unknown-linux-musl.drv'...
…
building
Preprocessing library for th-orphans-0.13.6..
Building library for th-orphans-0.13.6..
[1 of 1] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.o )
[1 of 1] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.p_o )
haddockPhase
Preprocessing library for th-orphans-0.13.6..
Running Haddock on library for th-orphans-0.13.6..
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: array-0.5.3.0, base-4.12.0.0,
binary-0.8.6.0, bytestring-0.10.8.2, containers-0.6.0.1, deepseq-1.4.4.0,
ghc-boot-th-8.6.3, ghc-prim-0.5.3, integer-gmp-1.0.2.0, mtl-2.2.2,
pretty-1.1.3.6, template-haskell-2.14.0.0, text-1.2.3.1, transformers-0.5.5.0
Warning: --source-* options are ignored when --hyperlinked-source is enabled.
Haddock coverage:
<command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
builder for '/nix/store/0qpmxlr0fm4bsvsj25bhm0m2j0ma139m-th-orphans-0.13.6-x86_64-unknown-linux-musl.drv' failed with exit code 1
```

I find it odd that the error message comes after `Haddock coverage:`. A blind guess: it fails building packages that use Template Haskell, as haddock cannot evaluate that when cross-compiling. Is there a way to disable all haddocks?

**Comment by nomeata** [comment]
Ok, not related to haddock, and also happens on nixpkgs `master` with GHC-8.6.4. Not sure what the story is.

**Comment by domenkozar** [comment]
Thanks for opening this, it is definitely planned to have statically linked executable. 

Currently it's not, so it has to be coming from nixpkgs, so that there's an existing binary cache. If we did switch to statically linked linux/macos executable, then binary cache wouldn't be required at all as the binary can be just fetched from releases so this would be great.

**Comment by nh2** [comment]
I provide a static `cachix` build in [`static-haskell-nix`](https://github.com/nh2/static-haskell-nix); you can see it's in the list of `working` executables that I've explicitly tested in https://github.com/nh2/static-haskell-nix/blob/97dd9f518ba15b5b72d603cd9d029767a2b39227/survey/default.nix#L697

For example, as described in [Building arbitrary packages](https://github.com/nh2/static-haskell-nix/tree/97dd9f518ba15b5b72d603cd9d029767a2b39227#building-arbitrary-packages), you should be able to get a static `cachix` right now with simply:

```bash
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/88ae8f7d.tar.gz nix-build --no-link survey/default.nix -A haskellPackages.cachix
```

(To make the cycle complete, there's also a `cachix` cache to save you time building `cachix` statically: `cachix use static-haskell-nix` before running the above.)

**Comment by nomeata** [comment]
Confirmed that 
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/88ae8f7d.tar.gz nix-build --no-link survey/default.nix -A haskellPackages.cachix
```
works, and results in a static binary of size 15MB, 3.3MB gzipped, which is a nice little improvement over the 9.79 MiB download, 46.36 MiB unpacked repoted above.

But this will probably have to wait for `pkgsStatic` to support building Haskell packages in mainline `nixpkgs`.

**Comment by nomeata** [comment]
Oh, and
```
$ nix-build -A pkgsMusl.cachix
```
(which is the variant where you don’t cross-compile, but simply build a whole system with musl) works on `nixpkgs` master too, since commit https://github.com/NixOS/nixpkgs/commit/3ff71fcc8b3dc1d17a823bd7f52b7685b4f5b1e1.

This command above still produces a shared executable, you have to set flags to create a static executable. And when I tried to do that naively, I got linker errors… so I guess waiting for `pkgsStatic` to include Haskell, or using @nh2’s work before it is merged, is probably your best bet.

**Comment by nh2** [comment]
For people's convenience, here's a static build of `cachix-0.2.0` I made with the latest `static-haskell-nix`:

* [cachix-0.2.0-static-haskell-nix.tar.gz](https://github.com/cachix/cachix/files/3228867/cachix-0.2.0-static-haskell-nix.tar.gz)

**Comment by domenkozar** [comment]
Now that cachix depends on Nix, this is going to get prioritized.

Blocked by https://github.com/NixOS/nixpkgs/pull/56281

**Comment by tazjin** [comment]
> then binary cache wouldn't be required at all as the binary can be just fetched from releases so this would be great

Personally I would much prefer to fetch it from the official binary cache due to the source hashes. Would it be possible to add the static cachix to nixpkgs?

**Comment by domenkozar** [comment]
That's my intention, nixpkgs would build the static binary, but instead of evaluating whole nixpkgs, static executable can just be directly substituted.

**Comment by domenkozar** [comment]
I think this is blocked until cachix gets to use GHC 8.8 with Cabal 3, that should make static compilation simple.

**Comment by nh2** [comment]
It's not really required, the patch I upstreamed to Cabal 3 only makes static-haskell-nix maintenance easier. Because with musl we have to build everything from scratch anyway, carrying the patch isn't a great blocker, just my time.

Perhaps the static-haskell-nix -> nixpkgs move should be a NixCon project?

**Comment by domenkozar** [comment]
That would be great, I'd pair up.

**Comment by domenkozar** [comment]
Now that Cachix pulls in Nix and builds with Rust, static builds are going to be quite some work.

Might use something like a tarball instead: https://pastebin.com/ev4M6Kff

**Comment by nh2** [comment]
Static rust builds don't seem too impossible. Alpine seems to do it successfully.

Can you elaborate a bit on how Cachix pulls in nix? Just in the closure? Is it for the patch that you need on Nix < 2.4?

**Comment by domenkozar** [comment]
Cachix uses inline-c-cpp to invoke Nix logic, so it's compiled with.

**Comment by domenkozar** [comment]
I'm thinking of https://cachix.org/api/v1/install returning something like:

`builtins.storePath /nix/store/...` where the store path would be determined by a specific commit per each platform.

That way linux, macos and aarch64 would take trivial amount of time to evaluate and for the rest there would be fallback to source.

It also would just substitute from cache.nixos.org and there's no need to do the hard work of static compilation.

**Comment by nomeata** [comment]
`builtins.storePath` is not documented in https://nixos.org/nix/manual/#ssec-builtins :-(

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nix/issues/3526

**Comment by domenkozar** [comment]
Similarly in Hydra https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/View/NixExprs.pm

**Comment by domenkozar** [comment]
@zimbatm pointed me to https://github.com/zimbatm/nix-experiments/tree/master/nix-snapshot which is something I'd like to play with for this use case.

**Comment by domenkozar** [comment]
As of today, Cachix will install in a few seconds for Linux and macOS. Using https://github.com/cachix/cachix-action should take ~4s.

Currently that's achieved by generating fake derivation that Nix won't know how to build from source, but it will find it in binary cache https://cache.nixos.org. 

You can see how that works by downloading https://cachix.org/api/v1/install and inspecting `default.nix` inside the tarball. 

I plan to also support aarch64 once it's stable again in nixpkgs. all other platfoms will fallback to downloading nixpkgs source.

**Comment by domenkozar** [comment]
This can be further reduced by making `nixMinimal` that Cachix would depend on, reducing the closure significantly by just removing aws sdk.
