### ISSUE TITLE
Setting up private cache on NixOS with untrusted user fails

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#186]
# error 

```
$ cachix use foo
/etc/nixos/cachix: createDirectory: permission denied (Permission denied)
```

# improvements

- note which method is being used in the output
- fix the bug?

**Comment by mynameisdaniil** [comment]
Similar problem on Ubuntu 18.04
`elm init` or `elm repl` produces
`elm: /usr/lib/node_modules: createDirectory: permission denied (Permission denied)`

**Comment by domenkozar** [comment]
I don't think elm has much to do with cachix :)

**Comment by arianvp** [comment]
Yes love to have this fixed. I don't use `/etc/nixos` to store my nixos config. I'd much rather have the following output:

```
[arian@t430s:~/Projects/generics-mrsop-diff]$  cachix use arianvp
Hey I see you're using NixOS and not running root. Please add the following to your NixOS config
{
  nix = {
    binaryCaches = [
      "https://arianvp.cachix.org"
    ];
    binaryCachePublicKeys = [
      "arianvp.cachix.org-1:/NYL/rC71vauTeFWVMJXXadA/2MfziDb+/1DlLLXUvw="
    ];
    
  };
}

```

**Comment by domenkozar** [comment]
There is `-d,--nixos-folder ARG    Base directory for NixOS  configuration (default: "/etc/nixos/")`, would that suffice to write it out wherever is your configuration?

**Comment by Rizary** [comment]
Is this the same with error `/etc/nixos/cachix: openFile: permission denied (Permission denied)` ? Because I have this error when using cachix in WSL ubuntu 18.04

**Comment by domenkozar** [comment]
Are you using NixOS or plain Nix?

**Comment by Rizary** [comment]
I am using plain Nix, in ubuntu 18.04 WSL (windows 10) version.

**Comment by domenkozar** [comment]
Does `/etc/NIXOS` or `/etc/nixos` exists?

**Comment by Rizary** [comment]
no it does not.

**Comment by domenkozar** [comment]
@Rizary what exact command are you running?

**Comment by Rizary** [comment]
@domenkozar 
`cachix use all-hies`

**Comment by domenkozar** [comment]
@Rizary did you manage to resolve this? I still don't understand how you end up in that code path.
