### ISSUE TITLE
Documentation (+API)

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#19]
Although current HTTP API is served at https://cachix.org/api/v1/ - it's not finalized. In following months I'd like to gather feedback and document in-depth how cachix works and how to integrate it into different services (Hydra, other CIs, etc).

- [ ] remove `c` prefix in `NarInfoCreate` types
- [ ] tests all `ToJSON/FromJSON` outputs
- [ ] use tags http://hackage.haskell.org/package/servant-swagger-1.1.5/docs/Servant-Swagger.html#g:3

**Comment by domenkozar** [comment]
Thanks for feedback. 

No, cachix account is only necessary for creating binary caches and pushing/copying to them. For using a public cache, there's no need to have cachix account. I'll make sure this is addressed.

Funding: it's not entirely clear at this stage, but I have plans to add support for private caches and possibly add some premium features. It depends on feedback from users, I'd like to find a balance for project to be sustainable but also serve the Nix community.

**Comment by qrilka** [comment]
@domenkozar is it expected that at https://cachix.org/api/v1/ I read 
> This is a sample server Petstore server.

?

Actually I was looking for some user docs about cachix (basically for using other users repos) and the repository README give some of that but https://cachix.org/ is not that good from this point of view - it doesn't give me any hint about that.

**Comment by domenkozar** [comment]
That's a bug in some of the servant-swagger, I'll make sure it's updated, thanks for the ping.

> using other users repos

Can you explain what's your use case?

**Comment by qrilka** [comment]
Somehow I heard cachix mentioned many times but didn't start using it yet until I stumbled upon it on https://github.com/Infinisil/all-hies so the general question was - how to install it and what could you do with it as a CLI tool, so I go to cachix.org press "Get Started" and then I see some selection of private or public repo and the first reacion is WAT.
Theoretically "What?" section looks to be some sort of it but after I sign in I can't access that. Maybe it make sense to keep some information about cachix available after signing in even if a user didn't choose a repo yet?
Or maybe it's just me....

**Comment by domenkozar** [comment]
You're able to go back by logging out via the profile menu. I agree with this being cumbersome, planning to fix it.

**Comment by roberth** [comment]
Reopening because only part of the issue is currently being addressed.
 - [x] update servant-swagger to fix the "petstore" bug
 - [ ] make the landing page available after logging in

**Comment by domenkozar** [comment]
Ah, I didn't mean to close it.

**Comment by roberth** [comment]
GitHub didn't understand that you linked a comment rather than the whole thing.

**Comment by domenkozar** [comment]
this is fixed
