### ISSUE TITLE
Deleting cache completely

### ISSUE THREAD

**Issue by ghost** [cachix/cachix#199]
Is it possible to delete cache completely? Similarly to, for example, deleting repository from github.

**Comment by domenkozar** [comment]
Not through web interface yet, but you can tell me which one you want to delete and I'll do it.

**Comment by ln-nl** [comment]
> you can tell me which one you want to delete and I'll do it
It is absolutely not necessary! But i would like to havе this functionality in the future.
Thank you!

**Comment by NorfairKing** [comment]
+1 on this feature.

**Comment by NorfairKing** [comment]
It's mostly because I can't regenerate a signing key.

**Comment by domenkozar** [comment]
@NorfairKing I can regenerate the signing key for you for now if you contact support.

**Comment by NorfairKing** [comment]
@domenkozar No worries, I'll also just wait for this feature, it's no big deal.

**Comment by domenkozar** [comment]
Deleting a cache is possible for some time.
