### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#20]
Since binary caches can grow, there should be a way to configure a garbage collection strategy. I envision the simplest one that would cover 80% of use cases is: collect oldest uploads that go over certain date or storage size.

**Comment by k0001** [comment]
Or, collect things that haven't been downloaded recently. 

The “oldest” approach doesn't work that well when people don't update things frequently, which is quite common if, for example, you only update your pinned version of `nixpkgs` once every a couple of months. This is a common problematic situation when trying to pin `nixpkgs` and benefit from its binary cache at the same time.

**Comment by chris-martin** [comment]
It would be cool if cachix had a concept of "GC roots" like Nix does, to use as one of the eviction heuristics.

**Comment by domenkozar** [comment]
Exactly.

**Comment by bbigras** [comment]
If we use a tool like [nix-build-uncached](https://github.com/Mic92/nix-build-uncached) (which doesn't build stuff already in the cache), I'm guessing that the tool queries the cache to determine if something needs to be built or not.

Could the garbage collection uses those queries (and downloads) to determine if something is used or not?

**Comment by domenkozar** [comment]
Moved to #338

**Comment by domenkozar** [comment]
This has been around for a while: https://docs.cachix.org/garbage-collection.html

Let me know if there's something misisng or that could be improved.
