### ISSUE TITLE
cachix push has unclear help formatting

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#204]
```
$ /nix/store/l5ihwni9i78ahq45iwjg8vpqclwcwc3l-cachix-0.2.1-bin/bin/cachix push --help
Usage: cachix push [--compression-level [0..9]] NAME ([PATHS...] |
                   [-w|--watch-store])
  Upload Nix store paths to the binary cache

Available options:
  -h,--help                Show this help text
  --compression-level [0..9]
                           The compression level for XZ compression. Take
                           compressor *and* decompressor memory usage into
                           account before using [7..9]! (default: 2)
  -w,--watch-store         Run in daemon mode and push store paths as they are
                           added to /nix/store
```

**Comment by roberth** [comment]
It does support that, but the line break is unfortunate.
I guess we can add a certain number of spaces to force the whole parenthesized part to go on a new line.
Another way to fix it is to say that `push -w` is its own command, but even if deprecating and adding a new command might be the right thing to do, it is a bit radical for what can also be considered a text formatting issue :)

**Comment by domenkozar** [comment]
https://github.com/pcapriotti/optparse-applicative/issues/353

**Comment by domenkozar** [comment]
This will be fixed in next optparse-applicative release.
