### ISSUE TITLE
Support brotli/zstd compression besides xz

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#205]
In https://github.com/cachix/cachix/issues/55 it was pointed out that zstd/brotli both [can achieve much faster transfer speeds](https://community.centminmod.com/threads/round-3-compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.17259/).

**Comment by terlar** [comment]
It would be nice if this is revisited now when the zstd compression is supported in the stable release of Nix

**Comment by domenkozar** [comment]
This is on high priority list.

**Comment by domenkozar** [comment]
Coming soon :sunglasses:

**Comment by rkrzr** [comment]
We would also be very interested in this feature. We have recently set up a private Nix cache for our office, which uses Cachix as one of its upstreams, and we are now bottlenecked on `xz` decompression speeds.

**Comment by domenkozar** [comment]
It's in development :blush:

**Comment by domenkozar** [comment]
https://github.com/cachix/cachix/pull/472 will drop today
