### ISSUE TITLE
cachix 0.2.1 has a large closure size

### ISSUE THREAD

**Issue by vaibhavsagar** [cachix/cachix#206]
`cachix-0.2.1` seems to include unnecessary dependencies in the closure, e.g. `ghc-8.6.5`, which leads to it slowing down my CI builds, e.g. https://travis-ci.org/vaibhavsagar/presentations/builds/557692395.

**Comment by domenkozar** [comment]
This is due to an old Nix version on Travis. It's interesting this worked before as Nix expressions are identical.

**Comment by vaibhavsagar** [comment]
I don't think so, here's what happens with Nix 2.2.2: https://travis-ci.org/vaibhavsagar/presentations/builds/558014807

**Comment by domenkozar** [comment]
I can reproduce this now with `nix-env -f . -iA cachix --store $PWD/tmp` on nixpkgs.

I'm confused why this happens due to:

```
$ nix-instantiate -A cachix.meta.outputsToInstall --eval --strict
[ "bin" ]
```

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nix/issues/2990

**Comment by domenkozar** [comment]
Pushed https://github.com/NixOS/nixpkgs/commit/d4296584d1dc0181fa9deebd059d444c1fcd80a9 - will switch the installation tomorrow once it hits binary caches.

**Comment by domenkozar** [comment]
Deployed :)

**Comment by vaibhavsagar** [comment]
Thanks!
