### ISSUE TITLE
Cachix 0.3.0 failing on Travis MacOS

### ISSUE THREAD

**Issue by purcell** [cachix/cachix#228]
Thanks so much for Cachix - my current consulting client is using it commercially, and I’m now setting it up on a personal open source basis to provide a binary cache for CI-friendly builds of multiple Emacs versions.

Strangely, I’m finding that `cachix use` fails silently in the Travis MacOS environment, as seen by this broken job within a build that works flawlessly on the Travis Linux hosts: https://travis-ci.com/purcell/nix-emacs-ci/jobs/234593181

`cachix use` also works fine for me locally in MacOS 10.14, while I believe the MacOS on Travis is 10.13. Another key difference would be that Travis runs Nix 2.0.x, while I have 2.2.x locally. I see that [the `.travis.yml` for this project](https://github.com/cachix/cachix/blob/master/.travis.yml) itself has some special handling for MacOS - is that to work around a known problem?

**Comment by domenkozar** [comment]
Hey @purcell, I'm going to look into this right now. Either way, `cachix use` shouldn't fail without an error message.

**Comment by domenkozar** [comment]
Sadly Travis Nix integration is not in a good state.

You'll have to add the following to `before_script`:

```
- echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
- sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
```

I'm going to try to fix cachix so that it prints an error at least.

**Comment by domenkozar** [comment]
I get an expected error message in https://travis-ci.com/cachix/cachix/jobs/234860791, seems like something is fishy with the macos build of cachix 0.3.0.

**Comment by domenkozar** [comment]
Seems like it's a buffering issue, if I add `|| sleep 5` the error message is displayed in travis logs.

**Comment by purcell** [comment]
> Sadly Travis Nix integration is not in a good state.

I'd be very happy to help work on fixing that if it would help. 

> You'll have to add the following to `before_script`:

I'll give that a try, but I'm a bit surprised that you don't need the same thing in the Travis build here, since you're also using `cachix use` on Travis + MacOS.

**Comment by purcell** [comment]
> You'll have to add the following to `before_script`:

That indeed did the trick, thanks.

> Seems like it's a buffering issue, if I add `|| sleep 5` the error message is displayed in travis logs.

Maybe you need to flush output explicitly. Wouldn't be the first time I've seen that.

**Comment by Profpatsch** [comment]
I see the same issue, but the fix from above doesn’t work here:

```
    "install":
    - >-
      echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
    - >-
      sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
    - >-
      nix-env -iA cachix -f https://cachix.org/api/v1/install
    - >-
      cachix use lorri-test
```

Log: https://travis-ci.org/target/lorri/jobs/587535261

**Comment by domenkozar** [comment]
This should now work with cachix 0.3.4. Although I recommend using github actions over travis, it will solve a lot of pain: https://github.com/cachix/cachix-action

**Comment by Profpatsch** [comment]
Github Actions are still extremely beta, so I wouldn’t want to switch to them just now. Want to focus on different things than beta testing yet another broken CI system :)

But thanks, we’ll check it out!

**Comment by Profpatsch** [comment]
@domenkozar No cigar, sadly: https://travis-ci.org/target/lorri/jobs/593673545#L547

**Comment by Profpatsch** [comment]
Will this be supported again in the future?

**Comment by domenkozar** [comment]
I'd really suggest looking at github actions.

I'll take a look again why it's not flushing.

**Comment by jefdaj** [comment]
@domenkozar the `before_script` just worked for me. I'm using Nix 2.0.4 on Travis in case that helps anyone.

**Comment by domenkozar** [comment]
@Profpatsch is this still an issue? I see lorri is using cachix on macos now: https://github.com/target/lorri/blob/master/.travis.yml#L98

**Comment by Profpatsch** [comment]
No, we disable cachix on MacOS: 
https://github.com/target/lorri/blob/b2f1fe218ab95ce7c89c4b35644d01c4c1f1b21d/.travis.yml.nix#L8-L20

However, I will remove that clause to see what happens with a newer cachix version.

**Comment by Profpatsch** [comment]
I enabled it in https://github.com/target/lorri/pull/340, and it seems to work just fine now.

**Comment by domenkozar** [comment]
Thanks! :)
