### ISSUE TITLE
Push timeouts from travis

### ISSUE THREAD

**Issue by purcell** [cachix/cachix#234]
I'm finding that a previously-working Travis build [is timing out](https://travis-ci.com/purcell/nix-emacs-ci/jobs/238335888) in `cachix push` today, while the same operation works from my MacOS development machine just fine. Any guesses at a possible cause? ([.travis.yml](https://github.com/purcell/nix-emacs-ci/blob/master/.travis.yml))

**Comment by domenkozar** [comment]
Most likely related to Nix 2.3, investigating.

**Comment by domenkozar** [comment]
I've reverted cachix 0.3.2 bump for installers, this should resolve the issue.

Will change the release process to prevent this in the future.

**Comment by purcell** [comment]
Ah, great, thanks.
