### ISSUE TITLE
Authenticated caches

### ISSUE THREAD

**Issue by ElvishJerricco** [cachix/cachix#24]
Just an idea for the future. It'd be nice if caches could be configured to be private, so that it requires authentication to access. I suppose you could argue that merely having the hash of the build is authentication enough, but I'm not 100% sure on that. At the very least, cachix itself serves as an extra attack vector, since presumably admins can see all builds everywhere.

**Comment by domenkozar** [comment]
Hey @ElvishJerricco - I'm planning to add authenticated caches - you can subscribe to the form at https://cachix.org/#faq to get more updates as it rolls out.

**Comment by domenkozar** [comment]
This is going to be part of 0.2 tomorrow.
