### ISSUE TITLE
Simple scenario does not seem to use cachix cache

### ISSUE THREAD

**Issue by chrissound** [cachix/cachix#243]
**On my PC:**

I authenticated etc...

```
nix-build https://github.com/chrissound/SodiumSierraStrawberry/archive/v1.1.tar.gz | cat
echo "/nix/store/78ypjmz7w6gncwzx3cvvqh0xw7w61ws3-sodiumSierraStrawberry-0.1.0.0" | cachix push chrissound
All done.
```

**On server:**
```
[root@XenonKiloCranberry:~]# sudo cachix use chrissound
```
I then also added:
```
    imports = [ ./cachix.nix ];
```
And did a `nixos-rebuild switch`.

However when doing `nix-env -i -f https://github.com/chrissound/SodiumSierraStrawberry/archive/v1.1.tar.gz` it still seems to be building manually (this is on server).

Am I missing something?

Here is a partial log of `nix-env -v -i -f https://github.com/chrissound/SodiumSierraStrawberry/archive/v1.1.tar.gz`: https://gist.github.com/chrissound/2a2d9ec7d74f661c42831716fc22b14b

**Comment by domenkozar** [comment]
In https://github.com/chrissound/SodiumSierraStrawberry/blob/master/sodium.nix#L8

Instead of using `./.` use:

```
builtins.path { path = ./.; name = "source"; }
```

Implementation of `./.` unfortunately uses parent directory for the name, which means your hash changes based on where you install (which is a temporary directory for nix-env)

**Comment by chrissound** [comment]
Thank you for your help! :+1:
