### ISSUE TITLE
error: cannot download certdata2pem.py from any mirror

### ISSUE THREAD

**Issue by equalunique** [cachix/cachix#25]
The install command failed:

`nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
`
...
`trying https://anonscm.debian.org/cgit/collab-maint/ca-certificates.git/plain/mozilla/certdata2pem.py?h=debian/20170717`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
`
...
`curl: (22) The requested URL returned error: 404 Not Found
error: cannot download certdata2pem.py from any mirror
builder for '/nix/store/yr263pahwwzadxxzh5qk65i34dhax7rl-certdata2pem.py.drv' failed with exit code 1
`

I'm not sure how to specify the correct URL: https://salsa.debian.org/debian/ca-certificates/raw/master/mozilla/certdata2pem.py

**Comment by equalunique** [comment]
I was able to get around this using the commands associated with this commit to nixpkgs: https://github.com/NixOS/nixpkgs/commit/933d7f37ace7928c10c99f760d18c561f6a631b7

```
$ nix-prefetch-url https://salsa.debian.org/debian/ca-certificates/raw/debian/20170717/mozilla/certdata2pem.py
path is '/nix/store/0d00axdac4h8ffxrf90s5zh8xdw3r29z-certdata2pem.py'
1d4q27j1gss0186a5m8bs5dk786w07ccyq0qi6xmd2zr1a8q16wy
```

**Comment by nrolland** [comment]
so a "by default" fix will just involve the channels picking up with this commit ?
