### ISSUE TITLE
Bad archive: input doesn't look like a Nix archive

### ISSUE THREAD

**Issue by rtimush** [cachix/cachix#251]
It seems that I managed to upload a broken `nar` to the cache with cachix (version 0.3.4): https://tenpureto.cachix.org/wrjd3z9x1gix6bxy0m9p4djzjypkrpxh.narinfo
Unlike some previous issues (#147), the file is not empty, just the [content](https://tenpureto.cachix.org/nar/bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8.nar.xz) looks truncated, at least from the beginning.
The command line I used was
```
cachix push tenpureto -w &
nix-build --no-link -A ... | cachix push tenpureto
```
and it could have been also forcibly terminated it a couple of times. It runs on the CI, so I, unfortunately, have no chance to look at the nix store.

Will rebuilding and re-pushing to the cache work (I will re-build anyway, but it takes some time without the cache)? If not, can you please delete the broken archive?
If you want to investigate how it could happen, I will also be happy to help.

**Comment by rtimush** [comment]
After rebuilding, I can confirm that the uploaded `nar` is missing 32752 bytes from the beginning (which can be `2^15-16`, but can also be a random coincidence).

**Comment by roberth** [comment]
@rtimush do you know which version of cachix has uploaded the file?

@domenkozar All the other narinfo fields are consistent with the truncated nar. It seems like the error comes from `nix-store --dump`, conduit's `streamingProcess`, `conduit` or some low level component.

-----

I've attached the narinfo and nar files for completeness.
[files.zip](https://github.com/cachix/cachix/files/3848890/files.zip)

```
$ sha256sum bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8.nar.xz 
bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8  bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8.nar.xz
```

```
StorePath: /nix/store/wrjd3z9x1gix6bxy0m9p4djzjypkrpxh-integer-logarithms-1.0.3-lib-integer-logarithms-doc
URL: nar/bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8.nar.xz
Compression: xz
FileHash: sha256:bd11361f7dc8c701ddae2ea82853d63c07ad949051724f8d1fad30f8195c97a8
FileSize: 39280
NarHash: sha256:1xckxxcyr29xjyqwvig8571a15f0qk2p0g1zingk1rm12sasmm2l
NarSize: 225264
Deriver: d8n6qqzprpyyj8cdch9yif7xzx365vyp-integer-logarithms-1.0.3-lib-integer-logarithms.drv
Sig: tenpureto.cachix.org-1:ZVC9ou8xTyn7EFGEZQGE898dBw4TvP+vLK/4PzcjDIq8qRRHEPqbWIiUxIxrxFWbzD8IitUqP7SPPDmBfm+zAQ==
```

**Comment by rtimush** [comment]
@roberth it must be 0.3.4 (and nix version is 2.3.1)

**Comment by rtimush** [comment]
Just in case — here is the non-truncated nar: [full.nar.zip](https://github.com/cachix/cachix/files/3849000/full.nar.zip)

**Comment by domenkozar** [comment]
@rtimush I've deleted that narinfo. 

I've seen this happen three times now, but it's still not entirely clear what goes wrong. It would be ideal if we could see logs from build that uploaded this narinfo, there could be something interesting there.

If it's `nix-store --dump` not exiting with non-zero, this will be fixed with Haskell implementation of Nar serialization.

If it's conduit, that's going to be harder to track down.

It could also be just network.

**Comment by roberth** [comment]
@domenkozar I think we can rule out network because the narinfo is produced locally in a way that is correct assuming that the uncompressed nar was really like that.
This part of the code does not involve network afaict (except unix domain socket, but that doesn't seem like a realistic cause, particularly if nar stream is generated in nix-store process, not daemon (I'd have to check))

**Comment by roberth** [comment]
If it's nix-store --dump, we can detect this by validating the magic bytes.

**Comment by rtimush** [comment]
I found the GitHub Actions [run](https://github.com/rtimush/tenpureto/runs/303504485) that probably uploaded this nar, here is the full [log](https://github.com/rtimush/tenpureto/commit/e5e173e486d12cf9cc5516c7ca74b99d8f10a806/checks/303504485/logs).
It had to retry the upload, and that's the only unusual thing I see in the logs:
```
...
2019-11-14T19:04:25.7893907Z pushing /nix/store/wrjd3z9x1gix6bxy0m9p4djzjypkrpxh-integer-logarithms-1.0.3-lib-integer-logarithms-doc
2019-11-14T19:04:26.2549340Z [ 2 of 29] Compiling Data.Memory.Internal.Compat ( Data/Memory/Internal/Compat.hs, dist/build/Data/Memory/Internal/Compat.o )
2019-11-14T19:04:26.4043498Z pushing (retry #1) /nix/store/jxmmw4daaxr07hkzax2bdj69xjflm7ih-cereal-0.5.8.1-lib-cereal-doc
2019-11-14T19:04:27.3158425Z pushing (retry #1) /nix/store/wrjd3z9x1gix6bxy0m9p4djzjypkrpxh-integer-logarithms-1.0.3-lib-integer-logarithms-doc
...
```

@domenkozar, thanks for deleting the broken entry 👍

**Comment by domenkozar** [comment]
Thanks @rtimush, that gives us a bit more insight into the bug.

**Comment by utdemir** [comment]
I am also having the same issue:

```
these paths will be fetched (3.03 MiB download, 3.07 MiB unpacked):
  /nix/store/k1ddvgvdy2a5djyglmmwn1dwll32j06j-perl-5.30.0-man
copying path '/nix/store/k1ddvgvdy2a5djyglmmwn1dwll32j06j-perl-5.30.0-man' from 'https://utdemir.cachix.org'...
bad archive: input doesn't look like a Nix archive
error: build of '/nix/store/idvma1b6lhc1x70nffi7qddl921r0cf6-perl-5.30.0.drv' failed
```

Is there an easy workaround for that? eg. Can I build that derivation manually on that machine without using `cachix`?

**Comment by domenkozar** [comment]
@utdemir I've deleted that narinfo. The workaround is to pass `--substituters ''` when invoking `nix-build`.

**Comment by anmonteiro** [comment]
I'm getting the same with:

```
copying path '/nix/store/b1nvbnnjfvzq10341l8ydrj2nz9kjkwl-ocaml4.09.0-async_kernel-0.13.0' from 'https://anmonteiro.cachix.org'...
bad archive: input doesn't look like a Nix archive
```
and the latest cachix action

**Comment by domenkozar** [comment]
@anmonteiro deleted.

**Comment by anmonteiro** [comment]
@domenkozar apologies there seems to be another one:

```
copying path '/nix/store/5zpn15rm7la8dy2sacyqm7zn6p584dy7-ocaml4.09.0-core-0.12.3' from 'https://anmonteiro.cachix.org'...
```

**Comment by domenkozar** [comment]
Done :)
