### ISSUE TITLE
Push timeouts

### ISSUE THREAD

**Issue by nagisa** [cachix/cachix#253]
Currently cachix prints out something along the lines of

```
pushing /nix/store/2jsms9xbr9ryn5x3f51743h3hzqj5gjp-pkg-name-1
pushing /nix/store/3axfyzm3zpk9v2zq7i3fc8vnqglrhawh-pkg-name-2
pushing /nix/store/3j212krlhzhyvi66m93n5mllc59y1j8m-pkg-name-3
```

It would be great if it also printed out the size of each of the things being pushed.

Context: we are investigating a spurious issue where our jenkins jobs timeout when pushing outputs. It would help somewhat to see how large the push is, exactly.

**Comment by domenkozar** [comment]
See #175, but I got another report of the same issue. When did it start happening?

**Comment by domenkozar** [comment]
@nagisa I'd appreciate if you can get exact timestamp of when the package that takes a lot of time got printed as pushing and store hash of it.

**Comment by nagisa** [comment]
The first instance of the issue I can find is on Nov 15 20:13 UTC, The first report that I have of this issue is on Nov 15th 8:20 UTC. We don’t have logs that go further back, sadly.

The hashes of packages being pushed were:

```
20:13:07  /nix/store/169c4181r61yid24bbmxyrr0qv1xjqqd-X.drv
20:13:07  /nix/store/1h34l3c40sb9ai3l0kbyphk9xsry889n-X
20:13:07  /nix/store/4ppy2nyzmxqnihgil54zzj18asxn1k0k-X
20:13:07  /nix/store/72bsrvlp3bcckllnqq596bhbvyqy4dx6-X
20:13:07  /nix/store/99yh881f961j9yv3d20x85lw87bbzby8-X
20:13:07  /nix/store/b8l7mdbbp2jxpygq7ajs1hkqiarifd44-X
20:13:07  /nix/store/i9c5sradfgs0vz8p1l10dwxr3jxvsf0k-X.drv
20:13:07  /nix/store/ix898xcspwhl0bhg3j2bmrrqrfhzwshk-X
20:13:08  /nix/store/k7ks6gdj5sik9h85r3jzd2a719dzp9yh-X.drv
20:13:08  /nix/store/r9rckl08mq6si8mxcqrg36bpd6ppq200-X
20:13:10  /nix/store/wxrv86wq2iqyrmgfg1j4ryx3pyjzq66f-X.drv
```
