### ISSUE TITLE
cachix CLI command for removing/disabling cache

### ISSUE THREAD

**Issue by cdepillabout** [cachix/cachix#267]
It would be nice to have a `cachix` command for easily disabling or removing a cachix cache.

For instance, I added the `static-haskell-nix` cache:

```console
$ sudo cachix use static-haskell-nix
```

Later, I wanted to remove it, so I looked for a command like `cachix remove` or `cachix disable`, but it didn't exist.

I guess the command would simply just remove the `/etc/nixos/cachix/static-haskell-nix.nix` file (as well as reminding you to re-run `nixos-rebuild switch`?).

**Comment by asheshambasta** [comment]
I've also stumbled across this. And while I hate adding a "I've seen this too" comment; removing the file still doesn't get cachix to start ignoring that particular entry. 

Now; running any nix command results in:
```
warning: ignoring untrusted substituter 'https://cache.nixos.org'
warning: ignoring untrusted substituter 'https://all-hies.cachix.org'
warning: ignoring untrusted substituter 'https://ghcide-nix.cachix.org'
warning: ignoring the user-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
```

How does one then remove a cache from cachix completely?

**Comment by roberth** [comment]
Seems like you've also configured your user, not just your system. You can edit out the wrong bits from `substituters` and `trusted-public-keys` in `~/.config/nix/nix.conf`. Private cache users should also edit their `~/.config/nix/netrc`.

**Comment by asheshambasta** [comment]
Thanks @roberth. But I'm still a little confused. I only removed all-hies.nix from the cachix directory; but why are the warnings also issued for cache.nixos.org? Does that mean I also need to remove them? Why/How did deleting the all-hies.nix file cause these warnings?

**Comment by domenkozar** [comment]
See https://github.com/cachix/cachix/pull/548
