### ISSUE TITLE
Archive returns HTTP 500 

### ISSUE THREAD

**Issue by anmonteiro** [cachix/cachix#278]
The following URL is returning a 500, making my build fail:
https://anmonteiro.cachix.org/nar/8921ad2e6d87ab5c84c1c79e5798a922b2ca0fd1d7932fac5aa7f22fb63e2e0e.nar.xz

P.S.: I was torn on whether I should have opened this issue or emailed support. What should I do next time?

**Comment by domenkozar** [comment]
I've seen a couple of these in last few hours and I'm in contact with storage provider. No feedback yet, but I can confirm 500s are permanent.

**Comment by domenkozar** [comment]
@anmonteiro I deleted the file, could you restart?

**Comment by anmonteiro** [comment]
Thanks, there's another one: https://anmonteiro.cachix.org/nar/ffedf9f0e39f74e552b2bee18fe5694b39029c41d6fc56683e98ba356126baf9.nar.xz

**Comment by domenkozar** [comment]
deleted

**Comment by anmonteiro** [comment]
There's another one: https://anmonteiro.cachix.org/nar/987a4b3c743761d8ba27b007483fb785b4447f6962f3c06c876c6ec72677f6be.nar.xz

I suspect this won't be the last one. I should just invalidate an upstream dependency somehow to force everything to build again.

**Comment by roberth** [comment]
@anmonteiro that probably won't help. It's also happening on a freshly pushed path for me.

**Comment by anmonteiro** [comment]
No worries, then. This is for an open source build. I have an S3 binary cache for my private projects which I can use in the meantime. I'll wait until this is resolved. Thanks for the quick responses!

**Comment by domenkozar** [comment]
@roberth what's the nar url?

**Comment by anmonteiro** [comment]
@domenkozar thanks, the build actually passed now!

Feel free to close this one from my side.

**Comment by domenkozar** [comment]
The fix will be deployed by storage provider at 2pm PST, in about 4h.

**Comment by domenkozar** [comment]
I'm no longer seeing 500s and storage provider confirmed the issue has been fixed.
