### ISSUE TITLE
--nixos-folder argument ignored?

### ISSUE THREAD

**Issue by arianvp** [cachix/cachix#279]
I'm trying to let cachix write to an alternative nixos location but this isnt working
```
$ cachix use wire-server -m nixos --nixos-folder $(pwd)

Could not install NixOS configuration to /etc/nixos/ due to lack of write permissions.

Pass `--nixos-folder /etc/mynixos/` as an alternative location with write permissions.

```

Cachix version is `0.3.5`

**Comment by domenkozar** [comment]
It seems like only the message is wrong, does your user have write permissions to $(pwd)?

**Comment by arianvp** [comment]
Ah wait. I was running this on `0.3.0`. It seems to work on `0.3.5`

**Comment by domenkozar** [comment]
I've fixed the error message in https://github.com/cachix/cachix/pull/280
