### ISSUE TITLE
Optimise packages upload

### ISSUE THREAD

**Issue by AlexeyRaga** [cachix/cachix#28]
I noticed that uploading a package that already exists is as slow as uploading it for the first time.

It is very noticeable  on big packages, such as `llvm` or `ghc`:  every time I call `nix-build -A xxx | cachix push name` it seems to re-upload all the dependencies.

I would expect that if the package hash already exists in cache then `cachix` could skip uploading it and move on to the next package.

**Comment by AlexeyRaga** [comment]
Awesome, thanks!

**Comment by domenkozar** [comment]
@alexeyraga https://github.com/cachix/cachix/pull/37
