### ISSUE TITLE
Request: Add mode to print nix options for 'cachix use'

### ISSUE THREAD

**Issue by erikarvstedt** [cachix/cachix#281]
Currently it's hard to use cachix-generated nix settings for one-off tasks without touching global nix.conf files.
Also, when setting up temporary cache with `nix-use --mode *-nixconf` , it's impossible to automatically undo the results .

To address this, I propose a new `print` mode for `cachix use`, to be used like this:
```
cachix use mycache --mode print | read -a NIX_ARGS; nix-build "${NIX_ARGS[@]}" ...
```
In this mode cachix should print the relevant nix options in the form `--option opt value ...`, with appropriate shell quoting.

Meanwhile, here's a workaround to set up a cache that avoids writing to any user or system files:
```
cfgdir=/tmp/nix-conf
mkdir -p $cfgdir
HOME=$cfgdir cachix use mycache --mode user-nixconf
cat /etc/nix/nix.conf $cfgdir/.config/nix/nix.conf > $cfgdir/nix.conf
# Run nix command
NIX_CONF_DIR=$cfgdir nix-build ...
```

**Comment by domenkozar** [comment]
Do you think this might be a duplicate of https://github.com/cachix/cachix/issues/126

**Comment by erikarvstedt** [comment]
Yes, it's an exact duplicate. :cat:
