### ISSUE TITLE
Could not install NixOS configuration to /etc/nixos/ due to lack of write permissions

### ISSUE THREAD

**Issue by avdv** [cachix/cachix#287]
I am using NixOS. Running cachix with `cachix use -m nixos  all-hies` results in:
```
Could not install NixOS configuration to /etc/nixos/ due to lack of write permissions.

Pass `--nixos-folder /etc/mynixos/` as an alternative location with write permissions.
```
Using `strace`, I noticed:
```
stat("/etc/nixos/cachix", 0x4200108e30) = -1 ENOENT (No such file or directory)
poll([{fd=2, events=POLLOUT}], 1, 0)    = 1 ([{fd=2, revents=POLLOUT}])
write(2, "\n", 1
)                       = 1
poll([{fd=2, events=POLLOUT}], 1, 0)    = 1 ([{fd=2, revents=POLLOUT}])
write(2, "Could not install NixOS configur"..., 87Could not install NixOS configuration to /etc/nixos/ due to lack of write permissions.
```
Seems the directory is expected but missing... `sudo mkdir /etc/nixos/cachix` and retrying worked.

**Comment by domenkozar** [comment]
So you didn't run the original command with `sudo`?

**Comment by avdv** [comment]
Oversimplification, my bad...

Actually, I ran the first command as a normal user additionally with `--nixos-folder $(pwd)/foo`, with this directory existing. But the command failed as described above and only worked after I created the missing cachix folder.

**Comment by fghibellini** [comment]
Same problem.
Creating `cachix` folder withing `/etc/nixos` fixed it.

**Comment by domenkozar** [comment]
Fixed in https://github.com/cachix/cachix/commit/b19af3300db0e91d0277d626cfce4371f339a444
