### ISSUE TITLE
UnknownCA: generate-keypair fails to connect to API

### ISSUE THREAD

**Issue by dadada** [cachix/cachix#289]
When trying to run `cachix generate-keypair dadada` after successfully adding a token using `cachix authtoken`, cachix returns with the connection error below.

Connecting through curl or firefox appears to work just fine. Also tried running 
`nix-shell -p cachix --pure --run 'cachix generate-keypair dadada'`, but to no avail.

Maybe some weird issues with Cloudflare? I'm connecting from somewhere in Germany, if that helps.

```
cachix: ConnectionError (HttpExceptionRequest Request {
  host                 = "cachix.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Content-Type","application/json;charset=utf-8"),("Authorization","<REDACTED>"),("User-Agent","cachix 0.3.7")]
  path                 = "/api/v1/cache/dadada/key"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))))
```

**Comment by domenkozar** [comment]
How did you install Cachix? What OS are you using?

**Comment by dadada** [comment]
I'm using NixOS 19.09 and tried both the version from nixpkgs master and https://cachix.org/api/v1/install

**Comment by dadada** [comment]
I had `security.pki.certificateFiles` in my `/etc/nixos/configuration.nix` and am completely unsure why this had any effect, but it works after removing that. I have no other issues related to this setting.
