### ISSUE TITLE
(Question) Possible to make aarch64 build of cachix ?

### ISSUE THREAD

**Issue by 573** [cachix/cachix#295]
I would love to use cachix on my phone but to due to spare storage resources also build it on a remote machine using pkgsCross. What I tried doing for starters was:

```
nix-build -E 'with import <nixpkgs> {}; pkgsCross.aarch64-multiplatform.haskellPackages.cachix'
```

giving me (with disabled haddock):

> [13 of 14] Compiling Generics.SOP.Instances ( src/Generics/SOP/Instances.hs, dist/build/Generics/SOP/Instances.o )
ghc: this operation requires -fexternal-interpreter
killing process 15263: No such process
builder for '/nix/store/v6afwd1wz20w9zlwwgr47y024r5nszk8-generics-sop-0.5.0.0-aarch64-unknown-linux-gnu.drv' failed with exit code 1
building '/nix/store/s7hn6r70l1r6hck5ylfmxd35rk1x3ryp-splitmix-0.0.4-aarch64-unknown-linux-gnu.drv'...
cannot build derivation '/nix/store/aw3dypgrizwkmrs1d050vs5xw3kp0wsz-swagger2-2.5-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/85nc49a4fsm6fi52a5rjp175rp3kwnh0-cachix-api-0.4.0-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6px5n6zwa2cfd8da4xxwrlhrkq8s4bsk-cachix-0.3.7-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6px5n6zwa2cfd8da4xxwrlhrkq8s4bsk-cachix-0.3.7-aarch64-unknown-linux-gnu.drv' failed

Research shows that maybe Template Haskell usage is causing this.

Are there plans to support cross compilation though ?

**Comment by domenkozar** [comment]
This will need working aarch64 ghc compiler in nixpkgs, I can give it a try.

**Comment by roberth** [comment]
This should work. Hercules CI agent compiles with it, which includes cachix.

**Comment by domenkozar** [comment]
Blocked by https://github.com/NixOS/nixpkgs/issues/66277

**Comment by vcunat** [comment]
In the meantime, the default ghc on stable branches has binaries: [20.03](https://hydra.nixos.org/job/nixos/release-20.03/nixpkgs.haskell.compiler.ghc865.x86_64-linux), [19.09](https://hydra.nixos.org/job/nixos/release-19.09/nixpkgs.haskell.compiler.ghc865.x86_64-linux).

**Comment by domenkozar** [comment]
Ah, yes: https://hydra.nixos.org/build/116518901

**Comment by domenkozar** [comment]
@573 I'll fix this.

**Comment by domenkozar** [comment]
I've posted an update to https://github.com/NixOS/nixpkgs/issues/66277#issuecomment-637429616

**Comment by domenkozar** [comment]
Hopefully this will get merged on Friday and this can be fixed.

**Comment by domenkozar** [comment]
This is fixed on master, but please wait for hydra to verify in next few days.

**Comment by 573** [comment]
Tested on my phone and can confirm that cachix 0.3.8 builds on aarch64 via ghc883.
Thanks.
