### ISSUE TITLE
`cachix use` to print out nixos configuration.nix

### ISSUE THREAD

**Issue by pjan** [cachix/cachix#30]
or at least provide an option for that instead of writing it to the `nix.conf` file in the `XDG_CONFIG_DIR`.

e.g.:

Add the following to your configuration.nix:

```
nix.binaryCaches = [ https://pjan.cachix.org/ ];
nix.binaryCachePublicKeys = [ pjan.cachix.org-..... ];
```

**Comment by domenkozar** [comment]
What would the option be called, `--nixos`?

**Comment by dtzWill** [comment]
:+1:

Related but minor issue: `cachix use` as untrusted user does this:
```
warn: $USER is not in trusted-users, requiring sudo.

MustBeRoot "Run command as 'sudo' or upgrade to Nix 2.0.1 or newer."
```

First message is spot-on, but second is a bit off.  Made me double-check I didn't have some pre-2.0.1 Nix somehow being used/invoked xD.

**Comment by domenkozar** [comment]
Related #35

**Comment by domenkozar** [comment]
Should be very easy to implement once https://github.com/cachix/cachix/pull/66 is merged

**Comment by domenkozar** [comment]
Here we go: https://github.com/cachix/cachix/pull/68
