### ISSUE TITLE
WSL - warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy

### ISSUE THREAD

**Issue by razvan-flavius-panda** [cachix/cachix#300]
When running `nix-build | cachix push razvan-flavius-panda0ftagi` under WSL Ubuntu 20.04 I get following warnings every some period of time and never ending:

```shell
neo@DESKTOP-ICMT4M4:~$ nix-build | cachix push razvan-flavius-panda0ftagi
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy (SQLITE_PROTOCOL)
^Cerror: interrupted by the user

neo@DESKTOP-ICMT4M4:~$
```

In `/etc/nix/nix.conf` I have:

```
use-sqlite-wal = false
sandbox = false
```

**Comment by puffnfresh** [comment]
Known issue with WSL1, you should try WSL2

**Comment by razvan-flavius-panda** [comment]
@puffnfresh Oh no. I thought that Windows 10 was using WSL 2 being 2020 May and all.

**Comment by puffnfresh** [comment]
You can check version with:

```
$ wsl -l -v
  NAME               STATE           VERSION
* Ubuntu             Stopped         1
  nixos-20.03-pre    Stopped         2
```

**Comment by razvan-flavius-panda** [comment]
@puffnfresh That command only prints the help output for me.

**Comment by puffnfresh** [comment]
@razvan-flavius-panda that means you're on a version of Windows without WSL 2. You need to be on 18917 or higher.

**Comment by razvan-flavius-panda** [comment]
@puffnfresh Thank you. I will have a look, been busy. I will enable the Windows Insider program to make sure I get WSL 2.

**Comment by razvan-flavius-panda** [comment]
I enabled Windows Insider, did an update and I am still on version: 18363.815

**Comment by razvan-flavius-panda** [comment]
@puffnfresh Aight, now it started seeing the insider updates and is installing 19619.100. Will tell you how it goes.

**Comment by domenkozar** [comment]
@razvan-flavius-panda please open an issue on https://github.com/NixOS/nix if you have issues with WSL.
