### ISSUE TITLE
Nix-shell call doesn't seem to pick up binaries from Cachix

### ISSUE THREAD

**Issue by gvolpe** [cachix/cachix#310]
Hi @domenkozar ,

I'm trying to use Cachix actions [here](https://github.com/profunktor/redis4cats/pull/305/checks?check_run_id=725600751) but the binaries are not being picked up from Cachix or at least I only see outputs like the one below:

```
copying path '/nix/store/nfwa72049p49pc8fy41v5d4clrkbqr1l-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
```

According to [this comment](https://github.com/cachix/cachix-action/issues/13#issuecomment-567953646) calls to `nix-shell` should also be supported right?

FWIW I pushed the binaries from my `shell.nix` using the following command:

```
nix-store -qR --include-outputs $(nix-instantiate shell.nix) | cachix push scala-microsite
```

Any clues on what I'm missing?

**Comment by domenkozar** [comment]
@gvolpe interesting, seems like not everything is getting pushed. Don't understand yet why. Could you try using `cachix-action@master`?

**Comment by gvolpe** [comment]
Thanks for the quick response @domenkozar !

I just tried with `master` but got the same output:

```
these derivations will be built:
  /nix/store/v5i6ddcbrqvk4fvy92nlc2ffdv123lc1-ruby.drv
  /nix/store/y0l3af0bcc17i5jzh9zyvh9syvky0xpf-builder.pl.drv
  /nix/store/3h65b9qygrbhgpgr9pircs44zr56022q-jekyll-4.0.1.drv
  /nix/store/4afyk33s1d4mnq3f5mlazfd1cm40vl60-jekyll-4.0.1.drv
....
copying path '/nix/store/jpqlmf3wqg281j8fdz50kjl525pfsxjc-gnused-4.8' from 'https://cache.nixos.org'...
copying path '/nix/store/0s93dpvxn7vaaah3n1lgz0q0xqdfsbkj-gnutar-1.32' from 'https://cache.nixos.org'...
copying path '/nix/store/rr3dqkpp340s318v3bx1vprmx27zj9w8-Diff-0.4.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/vivx5j0mbyhy8jhq4nip93kv1bbcd3r0-StateVar-1.2-doc' from 'https://cache.nixos.org'...
```

Here's the corresponding job: https://github.com/profunktor/redis4cats/pull/305/checks?check_run_id=727255726

**Comment by domenkozar** [comment]
That's weird. I'll take a closer look tomorrow.

**Comment by domenkozar** [comment]
These are not substituted due to `allowSubstitutes = false;` set on the derivation. You can read more about it here https://nixos.org/nix/manual/#sec-advanced-attributes

Note that all of the derivations are in your cachix cache.

This flag is usually used as an optimization - it's quicker to build it locally than to substitute.

**Comment by gvolpe** [comment]
Thanks @domenkozar !

Does this mean that there's no point in using Cachix for my simple Nix shell?

**Comment by domenkozar** [comment]
Probably for the given shell there's not point really. 

If you add more packages that need compiling it would help.
