### ISSUE TITLE
Warn: groups found @wheel

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#313]
Cachix should support checking if user is part of a group

**Comment by jkachmar** [comment]
My reading of the original issue was that the user should be a part of `nix.trustedUsers`; is this correct or is there some nuance I’m missing?

**Comment by domenkozar** [comment]
There's a warning in between:

```
Warn: cachix doesn't yet support checking if user is trusted via groups, so it will recommend sudo
Warn: groups found @wheel
```

So essentially that user is trusted, but Cachix will still recommend setting trusted users because it doesn't interpret groups.
