### ISSUE TITLE
Browse public packages (and/or derivations)

### ISSUE THREAD

**Issue by toraritte** [cachix/cachix#32]
Do you plan on adding visibility options to packages so that these could be browsed by others?

I'm fairly new to `nix` and loving it, but I already see that the current `nixpkgs` repo is getting out of control and contribution is also not the friendliest.

Thanks a lot for all your efforts putting Cachix together!

**Comment by domenkozar** [comment]
@toraritte so you'd like to search over packages or executables?

**Comment by toraritte** [comment]
Would you confirm is the use case below would be a valid one?

That is, after creating a web service (Elixir/Phoenix/PostgreSQL/React), it  would be possible to bundle all up and just upload it to Cachix, correct? It could be cloned from the github repo and set up by going through the written instructions (install dependencies, create database etc.), but with a Nix package it would just one command.
Or I may be misunderstanding Nix entirely:)

**Comment by toraritte** [comment]
So this the perfect example of what I had in mind in this issue:
https://coq.cachix.org/

Thanks again!
