### ISSUE TITLE
Typo in error helptext for missing key in `cachix push`

### ISSUE THREAD

**Issue by con-f-use** [cachix/cachix#320]
```
$ cachix push <destination>                                                                                                                                                                             

Signing key not found. 

It is generated by `cachix generate-keypair <name>` and stored in ~/config/cachix/cachix.dhall

There are a few options why this happened:

[...]
```

The path is probably supposed to be `~/.config/cachix/cachix.dhall`, i.e. missing the dot before `config`. 
However, it might be a more severe problem, because for me cachix 0.3.8 cannot find the key in either location, despite it being there. I have to set the `CACHIX_SIGNING_KEY` environment variable until things start to work.

**Comment by domenkozar** [comment]
Thanks fixed the typo.

There are quite a number of people (including myself) for which this works, so there must be something strange going on in your environment.

**Comment by domenkozar** [comment]
@con-f-use did you manage to resolve it?

**Comment by con-f-use** [comment]
Not really but I also failed to reproduce it on another machine.

**Comment by domenkozar** [comment]
It would be interesting to see what went wrong so I can produce better instructions how to debug when it happens.

**Comment by domenkozar** [comment]
Closing as there's no way to reproduce.
