### ISSUE TITLE
Cachix push returns 502 error if more than ~2000 dependencies need to be pushed

### ISSUE THREAD

**Issue by soareschen** [cachix/cachix#322]
Using the command `nix-store -qR --include-outputs $(nix-instantiate shell.nix) | cachix push <my-store>`, if the pipe result has more than around 2000 dependencies that need to be pushed, the API endpoint at cachix.org returns HTTP 502 bad gateway error served from Cloudflare.

The current workaround is to save the artifact list into a file, and split it in 2000 lines to be pushed separately. Nix artifacts that have been pushed before can be re-pushed over the 2000 lines limit without error.

**Comment by domenkozar** [comment]
This should be fixed as of a few minutes ago - could you try again?

**Comment by soareschen** [comment]
Thanks for the quick fix! I don't currently have that many dependencies to push, but it seems to work. Closing this then.
