### ISSUE TITLE
unable to download 'https://cachix.org/api/v1/install': SSL peer certificate or SSH remote key was not OK (60)

### ISSUE THREAD

**Issue by idmyn** [cachix/cachix#326]
When I run `nix-env -iA cachix -f https://cachix.org/api/v1/install`

```
unable to download 'https://cachix.org/api/v1/install': SSL peer certificate or SSH remote key was not OK (60)
```

Not sure what's going on here, but I guess an SSL cert might have expired..? Or it's just my machine - not sure.

**Comment by domenkozar** [comment]
Do you still have this issue? There was a couple of minutes of downtime yesterday.

**Comment by idmyn** [comment]
Yeah I'm still having the issue. I'm digging around and it seems like it probably falls into the broader category of macOS SSL/cert errors like this one: https://github.com/NixOS/nixpkgs/issues/70939

I'd appreciate any tips, but I understand this might be a weird issue specific to my machine (although I'm working with a pretty fresh macOS install)

**Comment by idmyn** [comment]
solved it: https://discourse.nixos.org/t/ssl-peer-certificate-or-ssh-remote-key-was-not-ok-error-on-fresh-nix-install-on-macos/3582

My nix profile wasn't set up properly (NIX_SSL_CERT_FILE was missing) 😅
