### ISSUE TITLE
Deleting objects from the cache

### ISSUE THREAD

**Issue by antifob** [cachix/cachix#33]
Hi,

Thanks for the awesome project.

Is it possible to delete object from the cache? For example, if an error occured and a build containing private keys was pushed. This can also allow cache purging, so that unused builds are not kept indefinitely (à la garbage collection).

**Comment by domenkozar** [comment]
Garbage collection will be handled by https://github.com/cachix/cachix/issues/20, but there should also be a way to delete a store path. Until then, in case of security issues contact me at domen@enlambda.com

**Comment by antifob** [comment]
I cannot test this as I'm no longer using Nix, but this issue has been handled with care and thoughts it's greatly appreciated. The self-serve ability also makes a lot of sense.

As I wrote, I cannot comment on this any further, but think it's the right step. Thanks again and feel free to close this issue. :)

**Comment by danwdart** [comment]
It would be amazing if we could add a "Clear unused" flag which deletes all the paths which haven't been downloaded, such as when you accidentally push all your paths ending in `drv`!
