### ISSUE TITLE
Allow pushing of artifacts from other cache sources

### ISSUE THREAD

**Issue by soareschen** [cachix/cachix#333]
Use case: Our Nix packages are built on top of Haskell.nix using cache sources from `https://iohk.cachix.org` and `https://hydra.iohk.io`, and we push the Nix artifacts to our own Cachix store. The issue is now we not only have to ask our Nix users to `cachix use` our own Cachix store, but also run `cachix use iohk` and then manually add `https://hydra.iohk.io` to the user's `~/.config/nix/nix.conf`. This greatly complicates the instructions to ask our users to adopt Nix and Cachix for the project, and introduce more chance of misconfiguration.

The `cachix` command should allow us to push all Nix artifacts outside of `https://cache.nixos.org` to the target Cachix store, regardless of whether it has been cached elsewhere.

**Comment by domenkozar** [comment]
Hi @soareschen,

what kind of CI setup do you have? 

`cachix push` will push the whole runtime closure to your cache, but not build dependencies.

**Comment by soareschen** [comment]
This seems to be solved now, as I might be previously using the wrong approach to cache the Nix shell dependencies. This is fixed after updating my Cachix command to as follows:

```bash
nix-store --query --references --include-outputs \
    $(nix-instantiate release.nix) \
    | xargs nix-store --query --requisites \
    | cachix push $CACHIX_STORE
```
