### ISSUE TITLE
feature request: set last accessed for narinfo requests

### ISSUE THREAD

**Issue by bbigras** [cachix/cachix#338]
as discussed on https://github.com/Mic92/nix-build-uncached/issues/22

When using [nix-build-uncached](https://github.com/Mic92/nix-build-uncached), not everything is build and pushed to cachix every time so the garbage collection could remove important stuff.

**Comment by domenkozar** [comment]
I've deployed this to production, will monitor for another day or two (since now requesting narinfo means a write) before announcing this publicly.

**Comment by bbigras** [comment]
Awesome. Thank you so much!

**Comment by domenkozar** [comment]
Looks good! Going to publish a blog post today to explain the changes.

**Comment by bbigras** [comment]
It seems to work fine for me so far. Thanks again!
