### ISSUE TITLE
`push -w` on remote builder leads to system crash (out of memory)

### ISSUE THREAD

**Issue by DavHau** [cachix/cachix#339]
Hey, thanks for cachix!

I'm currently integrating it into my remote builder infrastructure.
To push my build results directly to cachix, I run `cachix -w --compression-level 0 {cache}` on the remote builder.

Problem:
As soon as I start a bigger build, cachix starts endless amount of processes, depleting the systems memory after a short time resulting in a total crash of the remote builder.

Not using the `cachix push -w` during the build and instead running `cachix push` after the build finishes, works fine.

I'm using cachix 0.3.8

**Comment by domenkozar** [comment]
Could you make a screenshot of processes/ resource usage? Some more information would help to better understand what's going on.

**Comment by domenkozar** [comment]
@DavHau I'm happy to help with this, but need to be able to reproduce this. Maybe we could do a shared video session?

**Comment by DavHau** [comment]
Sorry for the delay. Here a screenshot of htop while provoking the previously explained behaviour:
![image](https://user-images.githubusercontent.com/42246742/94938784-82a3b000-04fb-11eb-88af-df1df8733c11.png)
It just goes on and on like this, if i scroll down.


And shortly after, the machine is crashed:
![image](https://user-images.githubusercontent.com/42246742/94938985-b7b00280-04fb-11eb-9f95-add856b5ae9e.png)
Cachix is running inside a docker container.
I might be able to prepare a docker container for you which triggers the error, if that helps.

In general I'm working on a remote builder with fast cachix integration.
To already start uploading while a build is still in progress, my Idea was to run `cachix push -w` whenever a build starts. A finishing build would kill the `cachix push -w` process, and then push the remaining artifacts via a subsequent `cachix push`.

But even if no crash occurs, my strategy doesn't seem to work. Some files seem to be missing on cachix afterwards. Not exactly sure why. Maybe the cachix backend signals the second pushing process, that some files already exist, even they had only been partly uploaded by the previous process (which was killed)?

sure, we can make a video session if you like.
FYI, It's not a blocking issue on my side. Instead of pushing to cachix while building, I'm OK with pushing after the build, which works fine. This would just be an optimization for me.

**Comment by domenkozar** [comment]
This would be solved with #53 at least for better ergonomics.

Just to be clear, what does `build` mean in this context, `nix-build` invocation?

If you can prepare a docker image that would be ideal to observe. Or a video session would work :)

> But even if no crash occurs, my strategy doesn't seem to work. Some files seem to be missing on cachix afterwards. Not exactly sure why. Maybe the cachix backend signals the second pushing process, that some files already exist, even they had only been partly uploaded by the previous process (which was killed)?

Does that happen even if you do `cachix push` afterwards?

**Comment by domenkozar** [comment]
@DavHau could you try Cachix 0.5.1?

 I'd need a way to reproduce this either by having instructions or access to your setup.

**Comment by domenkozar** [comment]
Fixed in #353
