### ISSUE TITLE
how to push binary with nix build and nix develop

### ISSUE THREAD

**Issue by GTrunSec** [cachix/cachix#340]
This question related to the flakes feature. 

- nix develop (nix 3.0)
- nix build (nix 3.0)
- https://nixos.wiki/wiki/Flakes#Pushing_Flake_inputs_to_Cachix (it does not work. only pushed the flake input sources to cachix instead of binary cachix)
```
nix flake archive --json \
  | jq -r '.path,(.inputs|to_entries[].value.path)' \
  | cachix push $cache_name
```

**Comment by domenkozar** [comment]
@GTrunSec how about `nix path-info --json | jq -r '.[].path | cachix push $cache_name'`

Note that this will only copy outputs, not full build closure.

**Comment by GTrunSec** [comment]
thanks, I see.  it has solved my question about `nix build`. how about nix develop? similar to how to push cachix in  `nix-shell`

**Comment by domenkozar** [comment]
`nix develop --profile dev-profiile && cachix push mycache dev-profile`

**Comment by GTrunSec** [comment]
Thanks for your answer

**Comment by Coda-Coda** [comment]
> `nix develop --profile dev-profiile && cachix push mycache dev-profile`

Hi @domenkozar, thanks for this tip, just for anyone else who sees this, note there is a typo. The first `dev-profiile` should read `dev-profile`.
