### ISSUE TITLE
support a more selective watch mode via a queue+socket+post-build-hook

### ISSUE THREAD

**Issue by colemickens** [cachix/cachix#343]
Idea:

I really want to capture build outputs as they're produced, but I don't really like that `cachix watch` picks up things from unrelated builds.

It seems like this be fixed by utilizing a post build script. However, I don't like configuring it on the daemon because it's one extra step to do on remote builders, it would catch "all" builds again, and I try to keep my "buildargs" portable so that I always get cache hits, etc (this might be alleviated once flakes respects custom nix conf).

But, it seems like we would need to "queue" the signing+pushing still and do it out-of-band from the builds. That's where `cachix` can play a role:

1. Start cachix, listen on a socket, sign+push paths when told about them over the socket
2. Let the user use the post-build-hook to send paths to that socket on success nix build

```bash
# untested, example (can't remember if I need to force it to not interpolate OUT_PATHS yet)

cat<<EOF >/tmp/script.sh
echo "${OUT_PATHS[@]}"  | cachix --queue-socket /tmp/cachix.sock"
EOF

cachix --watch-socket /tmp/cachix.sock
nix build '.#hello' -L --option post-build-hook "/tmp/script.sh"
```

**Comment by domenkozar** [comment]
Is post-build-hook executed on the client or daemon side?

**Comment by domenkozar** [comment]
(you probably mean cachix where you say cargo?)

**Comment by colemickens** [comment]
yes, `s/cargo/cachix/g`, updated the original post.

I'm not sure if it's executed client side or daemon side, but if I stash `whoami` in the post-build-hook into a file and then check it, it says `root`...

**Comment by domenkozar** [comment]
Yeah I agree with this and I plan to experiment how feasible it is. I've laid down a plan in #53 and this is on the horizon soon!

**Comment by domenkozar** [comment]
Here's the plan how this will work:

Using async to start two concurrent threads. The first thread is doing stuff and feeding things to a channel. The second one is consuming from channel and doing things based on those message. To handle done case: `data Message = Done | Do Thing` would be the message passed, so second thread would exit on `Done` case.

I have then yet to figure out how to handle CTRL-C but this makes the happy case smooth.

**Comment by domenkozar** [comment]
Going to start next week.

**Comment by domenkozar** [comment]
Queue implemented in https://github.com/cachix/cachix/pull/353, what's left then is the interface for post-build-hook and sockets.

@colemickens are you sure that post-build-hook works when specified on the client?

**Comment by colemickens** [comment]
Yes. I've implemented this in my own tool that has some other big
differences from cachix. We can share notes later if you want.

**Comment by domenkozar** [comment]
Cool - I'm going to implement `push-run` first and then also the build hook handling. Happy to compare - one thing that cachix does well is that it ensures whole closure is present in the cache.

**Comment by domenkozar** [comment]
Prioritizing this one as it's needed for https://github.com/cachix/cachix-deploy-hetzner-dedicated

**Comment by domenkozar** [comment]
`watch-exec` should set `$NIX_USER_CONF_FILES` that sets the build hook, while launching the process where the hook queues all the builds (so that it's more or less async).

**Comment by domenkozar** [comment]
similiar approach: https://github.com/nix-community/queued-build-hook

**Comment by domenkozar** [comment]
https://blog.cachix.org/posts/2024-01-12-cachix-v1-7/
