### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [cachix/cachix#344]
It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by domenkozar** [comment]
```
[__0] rejecting: cachix-0.3.8 (conflict: pkg-config package nix-main==2.0 ||
>2.0, not found in the pkg-config database)
```

Do you have any idea how to fix this for hackage?

**Comment by expipiplus1** [comment]
No idea, sorry :+1: 

I don't rely on the Hackage builder at all.

Here's a nix expression for generating Hackage compatible doc tarballs:

```
  docDrv = drv:
    (overrideCabal drv (drv: {
      doHaddock = true;
      haddockFlags = [ "--for-hackage" ];
      postHaddock = ''
        mkdir -p "$doc"
        tar --format=ustar -czf "$doc/${drv.pname}-${drv.version}-docs.tar.gz" -C dist/doc/html "${drv.pname}-${drv.version}-docs"
      '';
    })).doc;
```

**Comment by domenkozar** [comment]
It's now part of https://hackage.haskell.org/package/cachix, note that the API is needs quite some cleaning up and the version reflect CLI stability, not Haskell API PVP.

**Comment by expipiplus1** [comment]
Thank!

**Comment by domenkozar** [comment]
Added also for 0.6.0 and documented steps in 57597791adb7a9d505da900c0e29b66e6afd9f78

**Comment by expipiplus1** [comment]
Thanks!
