### ISSUE TITLE
Error 1016 Origin DNS error - cloudfare

### ISSUE THREAD

**Issue by d1egoaz** [cachix/cachix#356]
While trying to download this file
https://nix-community.cachix.org/nar/4f56620814073de4a24781846d8ea9a2c8c0df3007615517f922cb9991f3a7a7.nar.xz

I'm getting the following error:
```
copying path '/nix/store/yr6wi7h3gj5iq3w0i00na95lz9f173l5-source' from 'https://nix-community.cachix.org'...
warning: unable to download 'https://nix-community.cachix.org/nar/4f56620814073de4a24781846d8ea9a2c8c0df3007615517f922cb9991f3a7a7.nar.xz': HTTP error 530; retrying in 279 ms
warning: unable to download 'https://nix-community.cachix.org/nar/4f56620814073de4a24781846d8ea9a2c8c0df3007615517f922cb9991f3a7a7.nar.xz': HTTP error 530; retrying in 556 ms
```
 I'm using cloudfare 1.1.1.1 dns,

If I open the URL in a browser I get:
![image](https://user-images.githubusercontent.com/950087/107833376-e78fd200-6d47-11eb-9bbf-41d708c0f712.png)

I'm not sure if this is the right place to report this issue.

The file is being downloaded from this overlay:
```nix
  emacs_community_overlay = (import (builtins.fetchTarball {
    url =
      "https://github.com/nix-community/emacs-overlay/archive/master.tar.gz";
  }));

..       package = unstable.emacsGcc; ....

```

**Comment by domenkozar** [comment]
It was an upstream DNS issue that was resolved a few hours later.
