### ISSUE TITLE
How to push after build?

### ISSUE THREAD

**Issue by jmatsushita** [cachix/cachix#360]
Maybe a good topic for the FAQ? If I nix-build withoiut `watch-exec`  or `watch-store` how do I push the cache?

**Comment by jmatsushita** [comment]
@arianvp Gave me the answer:
> `build_deps=$(nix-store --query --requisites $(nix-instantiate   ./nix -A your-attribute))`  gives you all the build-time dependencies
> `nix-store --realise $build_deps` gives you all the output paths of all the build-time dependencies
> problem is that it will fetch all build-time dependencies first. (even things like bash bootstrap) whilst otherwise you'd only fetch the runtime dependencies of your immediate dependencies
> but yeh  `nix-store --realise $build_deps | cachix push blah` should do the job. it might download a bit too much though

**Comment by jmatsushita** [comment]
Digging a bit more into this, using `nix-store --query --requisites` captures too much. Since it queries the whole graph (including build time dependencies of build time dependencies, all the way down).

A somewhat inelegant solution (apart from not forgetting to use `cachix watch-exec` next time) is to pick a few layers up using `--references`. For instance for me:
```
$ build_deps=$(nix-store --query --references $(nix-instantiate ./shell.nix))
$ echo $build_deps | wc -w
23
$ nix-store --query --references $build_deps | wc -w
270
$ nix-store --query --references $(nix-store --query --references $build_deps) | wc -w
847
```

Whereas the whole graph with `--requisites`

```
$ nix-store --query --requisites $(nix-instantiate ./stack-deps.nix) | wc -w
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
2472
```

Then I found that using `nix-store --realise $build_depth_3` would not output build results paths on a subsequent runs, since the build products are already there. So using `--query --outputs` works consistently.

Finally since the `--references` contain also shell scripts and not only derivations, I had to filter to only pass derivations to the `--output` query.

Here's the resulting recipe:
```
build_depth_1=$(nix-store --query --references $(nix-instantiate ./shell.nix))
build_depth_2=$(nix-store --query --references $build_depth_1)
# check if you think you went deep enough
echo $build_depth_2 
build_depth_3=$(nix-store --query --references $build_depth_2)
# are we at the bottom yet?
echo $build_depth_3 
# now let's only keep `.drv` paths.
build_deps=$(echo $build_depth_3 | tr " " "\n" | grep '\.drv$' | head -n -1 | tr "\n" " ")
# now get all the outputs from these derivations and push them to cachix
nix-store --query --outputs $build_deps | cachix push my-cache
```

Voilà!

**Comment by domenkozar** [comment]
There's now https://docs.cachix.org/pushing that explain this in detail, let me know if something is missing!
