### ISSUE TITLE
Support authtoken on stdin

### ISSUE THREAD

**Issue by remexre** [cachix/cachix#363]
The CI platform I use (builds.sr.ht) has `set -x` on (which is useful!).
However, this results in a command like `cachix authtoken $(< ~/.cachix-auth-token)` leaking the auth token in the logs, since `set -x` logs after expansion of variables, command substitutions, etc.

Would it be reasonable to read the auth token from stdin if none is provided to the CLI, or if `--stdin` is passed or something?
(I'll submit a PR if so.)

**Comment by domenkozar** [comment]
Reading it from stdin if none is provided sounds good to me.
