### ISSUE TITLE
Provide a statically linked binary

### ISSUE THREAD

**Issue by simonvpe** [cachix/cachix#374]
I'm trying to optimize my build containers that I run on gitlab.com but just adding cachix to the image increases the image size by ~4GB. I've tried manually walking the dependencies for cachix and bringing in exactly the right shared obejcts it needs but when I do that I'm getting the error below.

I've made sure I can `curl` to 'https://cachix.org` and now I'm pretty much stuck. It'd be pretty sweet to have a statically linked binary that doesn't bring in the whole universe just for being able to upload a few binaries to a server.

```
bash-4.4# cachix use leash-lang-leash
warning: the group 'nixbld' specified in 'build-users-group' does not exist
cachix: ConnectionError (HttpExceptionRequest Request {
  host                 = "cachix.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept","application/json;charset=utf-8,application/json"),("Authorization","<REDACTED>"),("User-Agent","cachix 0.6.0")]
  path                 = "/api/v1/cache/leash-lang-leash"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "cachix.org", service name: Just "443"): does not exist (No address associated with hostname)))
```

I'm using the flake btw, when installing from `nix-env -iA cachix -f https://cachix.org/api/v1/install` it seems to work better but that's not something that fits me very well since I want my containers to be pre-built when I launch them.

**Comment by domenkozar** [comment]
Duplicates #184 

```
$ du -shc $(nix-store -qR /nix/store/q0lqpbbxcn2y4f23nhms7ncj7gvwbid1-cachix-0.6.0/bin/cachix)
...
150M	total
```

It's 150M, but that's mostly Nix also in the closure so if you install Nix from the same commit as Cachix it should really be about 50M extra.

One way to pull in cachix would be to `nix-store -r /nix/store/q0lqpbbxcn2y4f23nhms7ncj7gvwbid1-cachix-0.6.0` (assuming Linux). 

I wonder how you got to 4GB closure?

**Comment by simonvpe** [comment]
From what I can tell when bringing in cachix from a flake you can't configure the nixpkgs version to use, the flake imports `default.nix` passing the current system as argument, and then the nixpkgs version is pinned through niv rather than by the flake.lock. So what you're describing, to use the same nixpkgs version for cachix and nix isn't really possible at this point.

The "correct" way would be to pass nixpkgs as an argument to default.nix when importing it in the flake so that you can use the usual techniques for synchronizing nixpkgs versions cross-flakes.

If you want to I can prepare a PR for that, but I have other things to do so I'd want some form of confirmation that it's something you'd merge it if I do it.

Regarding your suggestion about hard-coding the store path -  that's not really how you normally do things, I think most nix users would want to follow common procedures for bringing in dependencies through either flakes or overlays, or both.

**Comment by domenkozar** [comment]
> From what I can tell when bringing in cachix from a flake you can't configure the nixpkgs version to use, the flake imports `default.nix` passing the current system as argument, and then the nixpkgs version is pinned through niv rather than by the flake.lock. So what you're describing, to use the same nixpkgs version for cachix and nix isn't really possible at this point.
> 
> The "correct" way would be to pass nixpkgs as an argument to default.nix when importing it in the flake so that you can use the usual techniques for synchronizing nixpkgs versions cross-flakes by setting `inputs.cachix.nixpkgs.follows = "/nixpkgs"` in your flake.
> 
> If you want to I can prepare a PR for that, but I have other things to do so I'd want some form of confirmation that it's something you'd merge it if I do it.

:+1: for making this configurable!

> Regarding your suggestion about hard-coding the store path - that's not really how you normally do things, I think most nix users would want to follow common procedures for bringing in dependencies through either flakes or overlays, or both, declaratively - not by running an installer or manually keeping track of derivation hashes.

Agreed! This serves as a workaround and I plan to work on static compilation as per #184

**Comment by domenkozar** [comment]
Writing https://nix.dev/tutorials/cross-compilation was the first step towards making this happen!

**Comment by domenkozar** [comment]
Latest status is at https://github.com/NixOS/nixpkgs/issues/188401

**Comment by domenkozar** [comment]
It's now possible to compile cachix statically, once the latest version lands in nixpkgs via `pkgs.pkgsStatic.cachix`.
