### ISSUE TITLE
Partial trust?

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#39]
The packages used to boot my laptop should probably (definitely) be from the official Nix cache or from my own builders.

Using cachix seems to require trusting everything at this level as well, which is rather unfortunate.

One might be willing to run some random person's build of a tool (perhaps in a sandbox) without wanting to trust them at a system level.

Diverted stores are partial solution but fully duplicate files already in /nix/store and have a number of problems re: direct execution, use with nix-env, etc.

This might require changes in Nix, depending on what thoughts are.

Maybe a good way to specify signatures used for nixos-rebuild, but I'm not sure that's the right granularity.

Thoughts? :)

**Comment by dtzWill** [comment]
Nevermind, at best this belongs as an issue on Nix I suppose.  It'd be cool if cachix had some magical solution but not sure that's reasonable :).

**Comment by domenkozar** [comment]
Sorry for long-awaited answer :) Yeah, this is in scope of Cachix, but not solvable in cachix itself. I think it needs also runtime isolation, so one way or another you end up with Docker or other containers.

On the other hand, I'll work on improving trust into users (by adding github<->cachix exposure) and long-term support binary-deterministic features.

**Comment by asymmetric** [comment]
@domenkozar could you expand on what features you mean regarding binary-determinism?

Also, what do you mean by github<->cachix exposure?

It might make sense to create 2 separate issues for these two points :)
