### ISSUE TITLE
Make `cachix deploy activate` command output logs from each machine

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#396]
The current behavior can be kept with `--async`.

- [ ] Allow downloading logs from the deployment
- [ ] Prepend log output with the agent name (ideally colored)
- [ ] Detect if the deployment was successful or not

**Comment by Kranzes** [comment]
I should also point out that it should send an error code if profile activation failed, that way something like a Hercules-CI effect will show that the deployment failed.

**Comment by domenkozar** [comment]
Another user requested this via support!

@sandydoo has a prototype stashed, so it will get done in the next weeks :v:

**Comment by domenkozar** [comment]
While this is almost ready, it will ship in v1.2

**Comment by domenkozar** [comment]
https://github.com/cachix/cachix/pull/482

**Comment by dhess** [comment]
Great! When operating in this mode, will the deploy command also exit with non-zero status when any agent’s activation fails?

**Comment by domenkozar** [comment]
Yeah :)

**Comment by domenkozar** [comment]
Implemented in https://github.com/cachix/cachix/pull/482, going to release 1.2 shortly
