### ISSUE TITLE
`openBinaryFile: permission denied` when cachix use

### ISSUE THREAD

**Issue by stefan-wullems** [cachix/cachix#399]
OS: Macos big sur 11.6
Apple silicon: No

Steps:
- I installed latest cachix using `nix-env -iA cachix -f https://cachix.org/api/v1/install`. I get version 0.6.1.
- I run `cachix use some-cache` and I get:
```
This user doesn't have permissions to configure binary caches.

You can either:

a) Run the same command as root to configure them globally.

b) Run the following command to add your user as trusted 
   and then try again:

  echo "trusted-users = root stefan.wullems" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
```
- I run `echo "trusted-users = root stefan.wullems" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon` and I get:
```
trusted-users = root stefan.wullems
```
- I run `cachix use some-cache` and I get:
```
cachix: /Users/stefan.wullems/.config/nix/netrc: openBinaryFile: permission denied (Permission denied)
```

Interesting:
- If I don't add myself to trusted users but run `cachix use -m "user-nixconf" some-cache` I also get `cachix: /Users/stefan.wullems/.config/nix/netrc: openBinaryFile: permission denied (Permission denied)`
- If I run `sudo cachix use -m "user-nixconf" some-cache`, whether I have added myself to trusted users or not, it works completely fine.

From this it looks like the problem is with trying to add a cache to the **local** configuration as a **non-root** user.

**Comment by domenkozar** [comment]
Does `/Users/stefan.wullems/.config/` exist? It's really strange you don't have permissions to create that file. Is `stefan.wullems` really your user when you run `cachix use some-cache`?

**Comment by stefan-wullems** [comment]
It seems like `stefan.wullems` really is the user:

```
$ (id -un && cachix use scrive)
stefan.wullems
cachix: /Users/stefan.wullems/.config/nix/netrc: openBinaryFile: permission denied (Permission denied)
```

I think I have strange permissions for the`.config` dir, but I'm not knowledgeable about it at all:
```
$ ls -ld ~/.config
drwx------  5 stefan.wullems  staff  160 Dec 16 15:46 ./.config
```

note: I'm not on a fresh install of macos. My employer configured the env so perhaps they configured it like this for a reason.

**Comment by domenkozar** [comment]
Can you also do `ls -ld ~/.config/nix` and `ls -ld ~/.config/nix/netrc`

**Comment by stefan-wullems** [comment]
```
$ ls -ld ~/.config/nix
drwxr-xr-x  4 root  staff  128 22 Dec 15:47 /Users/stefan.wullems/.config/nix
```
```
$ ls -ld ~/.config/nix/netrc 
-rw-r--r--  1 root  staff  181 22 Dec 16:50 /Users/stefan.wullems/.config/nix/netrc
```

**Comment by domenkozar** [comment]
How come your user config files are owned by root? That shouldn't be the case, I'm closing this as misconfiguration.
