### ISSUE TITLE
Cachix Deploy: any deployment that restarts the agent on macOS disconnects & requires manual intervention

### ISSUE THREAD

**Issue by dhess** [cachix/cachix#411]
Any deployment to macOS that happens to restart the Cachix Deploy agent causes the agent to sign off and never reconnect, so I have to log in to each Mac and deploy locally (manually) to get the deployment to work and the agent to reconnect. When the agent reconnects, the deployment shows up in the UI as "Canceled", but that's just a minor issue compared to the hassle of needing to deploy manually.

It's possible we're doing something wrong in our config, but there's not much to configure, so it's not clear what it would be.

**Comment by domenkozar** [comment]
I'm working on a fix that would solve this for all platforms at once. Needs more testing.

**Comment by dhess** [comment]
In our case, if you run the same deployment locally via `darwin-rebuild switch`, everything works fine and the agent starts up again with no problem. So if the agent would just reliably restart from `launchd`, that might resolve our particular issue (assuming the agent can try the deployment again, etc.).

We do see this in our logs when this occurs on macOS, BTW:

```
/Library/LaunchDaemons/org.nixos.cachix-agent.plist: Could not find specified service
Unload failed: 113: Could not find specified service
```

But if you're running it locally, at least, it restarts again anyway.

**Comment by domenkozar** [comment]
My naive solution didn't really work, so started changing the design how this all works to fix this for any platform.

The requirement is that while the agent daemon should be able to be restarted during the deployment to upgrade the agent, the deployment itself shouldn't be stopped.
