### ISSUE TITLE
Deploy: support home-manager

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#422]
Raise your requests for home-manager support in this issue and I'll prioritize it :)

**Comment by domenkozar** [comment]
@natecox @phijor @matthewes @luxus @davSanchez @Gerschtli It's now possible to use home-manager with Cachix Deploy thanks to @rycee 

I'll let you know once Cachix 1.1 is released to try it out!

**Comment by rycee** [comment]
If you want to try it before then use Home Manager together with https://github.com/nix-community/home-manager/pull/3380 together with https://github.com/cachix/cachix-deploy-flake/pull/1.

**Comment by domenkozar** [comment]
Since Cachix 1.1 has been released, here are the docs: https://docs.cachix.org/deploy/deploying-to-agents/#home-manager
