### ISSUE TITLE
"cachix: internal error: Itimer: Failed to spawn thread: Operation not permitted"

### ISSUE THREAD

**Issue by chreekat** [cachix/cachix#427]
On [this ghcs-nix pipeline](https://gitlab.haskell.org/bgamari/ghcs-nix/-/pipelines/55177), cachix-0.8.0 was picked up for the first time, which failed with the message `cachix: internal error: Itimer: Failed to spawn thread: Operation not permitted`.

Since those CI jobs dynamically pick the latest cachix version via `nix-env -iA cachix -f https://cachix.org/api/v1/install`, I was able to retry a job from a [previously-successful pipeline](https://gitlab.haskell.org/bgamari/ghcs-nix/-/pipelines/54541/builds) (which originally used cachix-0.7.0) and observe the same error in the [build-cabal-install-3_4_0_0 job](https://gitlab.haskell.org/bgamari/ghcs-nix/-/jobs/1128485).

My workaround was to use the cachix from nixpkgs, which is currently pinned to 21.11 (and thus cachix 0.6.0), which is [working once again](https://gitlab.haskell.org/bgamari/ghcs-nix/-/pipelines/55206).

The jobs run in a nixos/nix:2.9 docker image:

```
Using Docker executor with image nixos/nix:2.9.0pre20220511_5445738 ...
Pulling docker image nixos/nix:2.9.0pre20220511_5445738 ...
Using docker image sha256:beae0e60bf57cab6be6e86051de751fdbeed0b1c6509b8e91f0091c0267d3842 for nixos/nix:2.9.0pre20220511_5445738 with digest nixos/nix@sha256:aa7d512c768a4231ee4ab5656acb14e382c60df992f2c4a45d882f70bd42b6f3
```

I'm not sure this is a problem with cachix-0.8.0, but I thought you'd like to know about it. :)

**Comment by domenkozar** [comment]
Hey,

That's strange, sounds like some kind of a glibc problem. Did you try updating your nixos image too?

**Comment by domenkozar** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/issues/21604

**Comment by chreekat** [comment]
See also https://gitlab.haskell.org/ghc/ghc/-/issues/21477

which eventually links to https://github.com/NixOS/nixpkgs/pull/170900 . My guess is that the CI runner systems have the incompatible version of Docker, and cachix-0.8 has the affected version of glibc. I can bring this up with the runner system admin. :)

Closing as I don't think cachix can/should do much about this.
