### ISSUE TITLE
Agent names in the UI and API

### ISSUE THREAD

**Issue by dhess** [cachix/cachix#487]
It's possible to create an agent name in the UI like `foo.bar`, but when you use this name in the deployment JSON, it fails:

```
responseBody = "{\"error\":\"Invalid agent name foo.bar, it needs to be alphanumerical, possibly containing - or _\"}"
```

**Comment by domenkozar** [comment]
Fixed, now you can deploy using agents with a dot name

**Comment by yakimant** [comment]
@domenkozar,l ooks like error message was not changed.
I've got the same message, but issue was, that I had quotes, not dots.

**Comment by domenkozar** [comment]
You can't use quotes, only dots.
