### ISSUE TITLE
Feature request: remove revoked agents from the UI

### ISSUE THREAD

**Issue by dhess** [cachix/cachix#488]
I have several revoked agents in my deployment UI, and I'd like to remove them from the UI, but I don't see any obvious way to do that.

**Comment by domenkozar** [comment]
Would it work if we hid the agents that haven't been online for a week under a button like "show inactive agents"?

**Comment by dhess** [comment]
Eh, I dunno, that doesn't sound much better than the status quo. I probably want to know about inactive agents, but I most likely never want to see revoked agents again.

**Comment by domenkozar** [comment]
@Gerschtli @PlayerHereName this is now possible via the UI.
