### ISSUE TITLE
git tag should contain the cabal bump

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#489]

**Comment by sandydoo** [comment]
What are the options here? 
1. Remove and reapply the git tag after bumping the cabal versions
2. Use a script/tool to bump the cabal versions and apply the git tag locally. Then our CI just takes care of the release.

**Comment by domenkozar** [comment]
I was thinking 1) to have as much automation as possible. 

There's a 1 minute window where the tag will point to a different hash, but that won't impact anyone.
