### ISSUE TITLE
Installation method doesn't work

### ISSUE THREAD

**Issue by brainrake** [cachix/cachix#490]
nix 2.12.0 on NixOS unstable:
```
> nix-env -iA cachix -f https://cachix.org/api/v1/install
installing 'cachix-1.2'
error: unexpected end-of-file
```

**Comment by domenkozar** [comment]
Most likely your nix-daemon crashed, can you try again?

**Comment by brainrake** [comment]
it crashes every time i run this, but works on another machine. will look into it.
