### ISSUE TITLE
Manually cancelling a pending deployment

### ISSUE THREAD

**Issue by akirak** [cachix/cachix#498]
It would be nice if Deploy allowed the user to manually cancel a pending deployment.

Here is a use case: I am currently experimenting with automated deployment from GitHub Actions, but some machines are offline. At present, once activation is triggered, the service awaits for an agent infinitely, right? I can save computing resources by cancelling such runs.

It's difficult to prevent activation of only certain machines on CI, so it would make sense to cancel runs on the Cachix side.

**Comment by domenkozar** [comment]
You can now cancel in-progress and pending deployments

**Comment by akirak** [comment]
Thank you.
