### ISSUE TITLE
watch-exec does stuck after run

### ISSUE THREAD

**Issue by shyim** [cachix/cachix#501]
```
cachix watch-exec shopware devenv shell php -v
Watching /nix/store for new store paths ...
Building shell ...
warning: Git tree '/Users/shyim/Downloads/platform' is dirty
[1/1/10 built] building php-grpc-1.50.0 (buildPhase):  clang++ -I. -I/private/tmp/nix-build-php-grpc-1.50.0.drv-1/grpc-1.50.0 -I/private/tmp/nix-build-php-grpc-1.50.0.drv-1/grpc-1.50.0/include -I/private/tmp/nix-build-php-grpc-1.50.0.drv-1/grpc-1.50.0/main -I/private/tmp/nix-bui
error:
       error: interrupted by the user
^C^C^C^Czsh: killed     cachix watch-exec shopware devenv shell php -v
```

I have to kill it from different terminal. It hangs after `error: interrupted by the user` and does nothing anymore

**Comment by shyim** [comment]
It seems like to never stop even when the command finished

```
cachix --version
cachix 1.2
```

**Comment by shyim** [comment]
Downgraded to cachix 1.1 and it works 🙈

**Comment by domenkozar** [comment]
cc @sandydoo, this could be due to the new fsnotify?

**Comment by sandydoo** [comment]
@shyim, this is on macOS, right?

**Comment by sandydoo** [comment]
@domenkozar, I think it's that [`CNix.init` change](https://github.com/cachix/cachix/commit/85cef0f8f8f7c14edb17f327b48c4d81176393e4). I can replicate the behavior on macOS right from that commit. We probably have to add [that signal handler](https://github.com/hercules-ci/hercules-ci-agent/blob/d79e8b2ca8142335097222e78cdf9953f2183eed/hercules-ci-cnix-store/src/Hercules/CNix/Util.hs#L46) that passes the interrupt onto Nix.

**Comment by sandydoo** [comment]
Looks like `CNix.init` causes the process to hang/become unresponsive on darwin. I'll investigate some more tomorrow.

**Comment by sandydoo** [comment]
I've narrowed it down to [the signal handler thread](https://github.com/sandydoo/nix/commit/98e0ca9e023296ad568a776ddb143b6c8ca3a3a1) that Nix launches in `initNix`. It's blocking the int/term signals, but the handler thread isn't receiving the signals 🤷

**Comment by domenkozar** [comment]
@roberth have you observed similar behavior yourself?

**Comment by shyim** [comment]
If someone needs an workaround without downgrading :)

```
#!/usr/bin/env bash

cachix watch-store $1 &
cachixPid=$!

shift 1;

"$@"

kill $cachixPid
```

**Comment by sandydoo** [comment]
It's unfortunate that `initNix` is installing these signal handers. It seems really unnecessary if all we're doing is hooking into the Nix library to use the store API.

I assume this affects the Hercules agent on darwin as well, unless Robert has concocted some magic combination of linker/compiler flags that fixes this. 😂 

As a workaround, we can do the following:

1. Install the CNix handler which forwards the interrupt to Nix.
2. Unblock the signals that `initNix` blocks (big hack)
     ```haskell
     unblockSignals
       $ emptySignalSet
       & addSignal sigINT
       & addSignal sigTERM
       & addSignal sigHUP
     ```
3. Add `-fcompact-unwind` to the GHC options. This fixes https://gitlab.haskell.org/ghc/ghc/-/issues/11829 and prevents our client from re-throwing every C++ error.

**Comment by sandydoo** [comment]
Basic repro to hack on: https://github.com/sandydoo/nix-init-signal-handler-repro

**Comment by sandydoo** [comment]
Nix blocks signals with `sigprocmask(SIG_BLOCK...)` and then listens for signals with `sigwait`.
In Haskell, `installHander` uses `sigaction` to modify how signals are handled.
On Linux, `sigaction` receives signals that are blocked. On macOS, it does not.

**Comment by domenkozar** [comment]
One more reason to rewrite get closure function in Haskell and drop C++.

**Comment by roberth** [comment]
> It seems really unnecessary if all we're doing is hooking into the Nix library to use the store API.

Some initialization is necessary though, but I don't think we're questioning that, because of the earlier sqlite bug report.

> I assume this affects the Hercules agent on darwin as well, unless Robert has concocted some magic combination of linker/compiler flags that fixes this. joy

It runs in launchd, so not much of a problem as launchd kills it.

> 3\. Add `-fcompact-unwind` to the GHC options. This fixes https://gitlab.haskell.org/ghc/ghc/-/issues/11829 and prevents our client from re-throwing every C++ error.

You should do this regardless, as it is a requirement for running C++ on darwin. GHC 9.4 will enable this unwind info by default, but for now, you need to enable it yourself.



> One more reason to rewrite get closure function in Haskell and drop C++.

You'll have to talk to the store somehow, and doing it in-process with C++ is fast, because you talk directly to the daemon and you get to use the path info cache. Keep me posted if you're going to implement the daemon protocol ;)
