### ISSUE TITLE
deploy: add options to fire and forget

### ISSUE THREAD

**Issue by hugosenari** [cachix/cachix#504]
Current version of command activate waits until deploy is done

When agent is down, deploy command waits until it connect

Using it requires all agents to be up.

**Comment by sandydoo** [comment]
Hey, @hugosenari, you can use the `--async` flag to deploy the agents without waiting for the deployments to complete.

**Comment by hugosenari** [comment]
I'm using NixOS stable version (22-11), that has cachix v1.1 and that option is only available in v1.2

Thank you
