### ISSUE TITLE
"unable to download" errors

### ISSUE THREAD

**Issue by samuela** [cachix/cachix#507]
I get errors like
```
error: unable to download 'https://ploop.cachix.org/nar/0af0f5871fd29781e90c606ab2713066ba05e962647c9830dd96825330f269bf.nar.zst': HTTP error 200 (curl error: Failure when receiving data from the peer)
error: unable to download 'https://ploop.cachix.org/nar/aedc8b21ed388c8a4dd1820d78e5e9c61cc18c301a1e684896b5d29ef43a71bb.nar.zst': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer)
```
about once per day. The errors are intermittent and the same command usually works fine after a retry. 

This started a few weeks ago and I chalked it up to temporary network issues, but the problem doesn't seem to have gone away since then. Just raising awareness in case this was something that was not on the radar yet.

**Comment by domenkozar** [comment]
This is an upstream bug in Nix, it should be retrying these: https://github.com/NixOS/nix/issues/1254

**Comment by samuela** [comment]
ah gotcha, thanks for the pointer!!
