### ISSUE TITLE
unknown compression method 'zstd'

### ISSUE THREAD

**Issue by mpscholten** [cachix/cachix#508]
Since a while I've seen the `unknown compression method 'zstd'` error appear in the IHP community. It's typically caused by an outdated nix version.

Here's a recent screenshot from the IHP slack:

![Screenshot from 2023-02-27 19-31-03](https://user-images.githubusercontent.com/2072185/221672818-72a28824-04e7-4f04-99dd-51a38c718131.png)

Could cachix maybe detect an old nix version is used and then switch to a supported compression?

**Comment by domenkozar** [comment]
The problem is that the machines pushing to the cache aren't the same as the ones downloading.

I suggest making it a FAQ entry, those running two years old Nix should upgrade.

**Comment by mpscholten** [comment]
Ok thx, we'll do it that way 👍
