### ISSUE TITLE
Error: Unable to locate executable file: cachix

### ISSUE THREAD

**Issue by tartavull** [cachix/cachix#511]
Hello!

I'm getting a new error when running a workflow.

<img width="1088" alt="Screen Shot 2023-03-05 at 2 00 33 PM" src="https://user-images.githubusercontent.com/4648166/222980348-5da4d41b-b703-454c-8423-d7180fde1d4b.png">

Do you know what might be causing this issue?

**Comment by sandydoo** [comment]
Hey, @tartavull, there was [an issue](https://github.com/cachix/install-nix-action/issues/161) with `cachix/install-nix-action` and a new release of Nix. Please upgrade to `cachix/install-nix-action@v20`.

**Comment by tartavull** [comment]
Thank you!
