### ISSUE TITLE
How does one use cachix to share nix-shell environments?

### ISSUE THREAD

**Issue by cocreature** [cachix/cachix#52]
First of all, thanks for cachix! It’s an awesome project!

Now to my question: I have a bunch of projects that have fairly expensive (in terms of build time) development environments (e.g. they require debugging builds of LLVM) so cachix would be perfect for sharing these environments with other developers.
However, I’m not really sure what the best way of doing that is.

**Comment by cocreature** [comment]
Seems to work perfectly, thanks!

**Comment by domenkozar** [comment]
Let's leave this open until it's documented :)

**Comment by domenkozar** [comment]
In that case doing just `nix-shell shell.nix` should suffice.

**Comment by edude03** [comment]
@domenkozar hmm, I'm not sure we're on the same page, if I take the exact shell source from my example and put it in `shell.nix` and run `nix build -f shell.nix` I get

```
builder for '/nix/store/fgdz9pijvglcvzhypcl3k5v4idbmf5f8-some-shell.drv' failed with exit code 1; last 2 log lines:
  unpacking sources
  variable $src or $srcs should point to the source
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/fgdz9pijvglcvzhypcl3k5v4idbmf5f8-some-shell.drv' failed
```
Are nix-shell's not supposed to use `stdenv.mkderivation`?

**Comment by edude03** [comment]
Ah! Thanks! I see

**Comment by zimbatm** [comment]
Another strategy used by https://github.com/cachix/cachix-action is:

```
cache_name=foobar
# record all the existing paths in the store
nix path-info --all | grep -v '\.drv$' > /tmp/store-path-pre-build

# run your commands here. eg:
nix-shell --run "echo OK"

# at the very end, dump the diff to cachix
nix path-info --all | grep -v '\.drv$' | cat - /tmp/store-path-pre-build | sort | uniq -u  | cachix push ${cache_name}
```

The nice thing about this approach is that it doesn't need to carefully make sure that all the outputs or collected. Which can be quite difficult when using import-from-derivation or any nix wrappers.

**Comment by razvan-flavius-panda** [comment]
@domenkozar Hi, has this been documented? I have the same issue right now, trying to push all `nix-shell` build dependencies to cachix.

**Comment by razvan-flavius-panda** [comment]
Will the following warning cause any issues?

```
neo@nixos ~/P/haskell-editor-setup> nix-store -qR --include-outputs (nix-instantiate shell.nix) | cachix push fairy-tale-agi-solutions
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
```

**Comment by jappeace** [comment]
@razvan-flavius-panda 

It means the garbage collector will clean the result. But it doesn't matter since you pushed it to cache anyway.

**Comment by domenkozar** [comment]
This is now documented at https://docs.cachix.org/faq.html#is-there-a-way-to-cache-nix-shell

**Comment by fzakaria** [comment]
@zimbatm  @domenkozar @edude03 the only issue with your suggestion above & in the cachix documentation is it includes all transitive dependencies to build; which is **too broad**

Consider this _simple_ example:
```
let nixpkgs = import <nixpkgs> {};
in
with nixpkgs;
with stdenv;
with stdenv.lib;
mkShell {
  name = "example-shell";
  buildInputs = [chromium];
}
```

Ideally, I'd only want to cache **chromium** for my nix-shell.

However if you run the snippet given you get _way more_:
```bash
nix-store -qR --include-outputs $(nix-instantiate shell.nix) | head -n 10
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/b7irlwi2wjlx5aj1dghx4c8k3ax6m56q-busybox.drv
/nix/store/bzq60ip2z5xgi7jk6jgdw8cngfiwjrcm-bootstrap-tools.tar.xz.drv
/nix/store/wzdwpgqf2384hr2npma78mqillg5lv08-unpack-bootstrap-tools.sh
/nix/store/0zhkga32apid60mm7nh92z2970im5837-bootstrap-tools.drv
/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh
/nix/store/1i5y55x4b4m9qkx5dqbmr1r6bvrqbanw-multiple-outputs.sh
/nix/store/4ygqr4w06zwcd2kcxa6w3441jijv0pvx-strip.sh
/nix/store/6k829xz9v508ncxfcf2p1b8g1wq54946-patch-shebangs.sh
/nix/store/8zxndz5ag0p6s526c2xyllhk1nrn4c3i-audit-tmpdir.sh
/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh
```

```
nix-store -qR --include-outputs $(nix-instantiate shell.nix) | wc
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
   2093    2093  139650
```

Is there a sensible way to _only query_ the output?

**Comment by domenkozar** [comment]
That could be fixed by making shell.nix build a noop.

Currently there's no easy way to query that in Nix: https://github.com/NixOS/nix/issues/1245

**Comment by fzakaria** [comment]
@domenkozar I suspect a noop won't be enough. 

A dummy file should be the derivation output that just has the list of the `buildInputs` in it. 

This is because Nix greps for the buildInput hashes to determine the runnable set.  

That might be a worthy improvement to mkShell to always output.

**Comment by fzakaria** [comment]
@domenkozar and others -- I opened https://github.com/NixOS/nixpkgs/issues/95191 with a proposed solution.
Please let me know what you think.

**Comment by fzakaria** [comment]
For those reading this pullrequest here is a much **saner** transitive set to cache for **shell.nix**

```bash
nix-store --query --references $(nix-instantiate shell.nix) | \
xargs nix-store --realise | xargs nix-store --query --requisites | cachix push $NAME
```

**Comment by avanov** [comment]
What is the right way of using this pipe with `nix copy`? it reports `error: path '/nix/store/fzmkblzbsmqlsw7dvch92k92mp7q5vlh-nix-shell' is not valid` for me
