### ISSUE TITLE
Add signal handling to the daemon

### ISSUE THREAD

**Issue by asymmetric** [cachix/cachix#53]
In order to avoid having to call `cachix push` [twice](51), we can do the following:

* Add signal handling to the daemon mode
* Have a signal that, when received, finishes pushing and then exits
* Run the daemon in a job in parallel with `nix-build`
* Send that signal after `nix-build`

**Comment by dtzWill** [comment]
If actual signal handling is not easily supported (dunno), any mechanism for communicating "please stop looking for new paths to upload and exit after finishing the current queue" would (at least in my opinion) address the motivation for this issue.  Agreed this would be neat particularly for the CI case :).

**Comment by domenkozar** [comment]
I've looked into this today. Turns out we can't just use `mask_` as Async doesn't trigger `UserInterrupt` exception inside the threads. I need to research if this is even possible with `async` package.

**Comment by domenkozar** [comment]
I've opened the issue on async package: https://github.com/simonmar/async/issues/91

**Comment by domenkozar** [comment]
Seems like with some signaling between main thread and workers, we can use http://hackage.haskell.org/package/async-pool

**Comment by roberth** [comment]
*Re: signaling*
Here's [my idea](https://gist.github.com/roberth/7f5fae2178e7574eb7dcdd0dc6e32246). Should compose nicely with `async` or other concurrency stuff.
Untested, but typechecked :)

**Comment by Infinisil** [comment]
How about having a command like
```bash
cachix push-watch [command]
``` 

Which first starts watching the Nix store for new derivations, then calls the given command, and stops watching and finishes uploading when the command exits.

**Comment by domenkozar** [comment]
I like that since it can be then used everywhere regardless of the integration.

**Comment by bflyblue** [comment]
I really like that too and would love to see support for `push-watch`! :)

**Comment by domenkozar** [comment]
Since this is fixed and foundamentals are in master, I've moved `run-watch` command into https://github.com/cachix/cachix/issues/354 that should be easy to add now.

**Comment by domenkozar** [comment]
Released both as part of 0.6.0!
