### ISSUE TITLE
Is there a way to use multiple caches?

### ISSUE THREAD

**Issue by tartavull** [cachix/cachix#536]
https://github.com/tartavull/alfredo/blob/main/.github/workflows/test.yml#L15

I want to first ping cuda-mantainers and if that fails use my personal cache as a backup.

**Comment by tartavull** [comment]
Thank you for the quick response, I've been able to use this to setup my personal cache. But I'm not sure if there is something required to setup two cache and make one the fall back from the other.

**Comment by domenkozar** [comment]
Nix will use the caches in the order they are defined, does that work for your use case?

**Comment by tartavull** [comment]
Thank you so much!
