### ISSUE TITLE
Fails with self-hosted runner.

### ISSUE THREAD

**Issue by tartavull** [cachix/cachix#540]
Should cachix work out of the box when using a self-hosted runner?

I'm getting the following error
<img width="1251" alt="Screenshot 2023-06-03 at 1 39 04 PM" src="https://github.com/cachix/cachix/assets/4648166/993a2a37-c405-47e3-a3cd-0e43d9e44b83">

**Comment by domenkozar** [comment]
You will need to configure Nix to trust the current user as instructed.

There's a tiny bit of setup that install-nix-action takes care of.

**Comment by domenkozar** [comment]
@tartavull does that help?

**Comment by tartavull** [comment]
It did! thanks again!
