### ISSUE TITLE
`cachix watch-exec` fails with `CppStdException "path '/nix/store/... is not valid" (Just "nix::InvalidPath")`

### ISSUE THREAD

**Issue by erikarvstedt** [cachix/cachix#547]
I've only witnessed this bug when `/nix/store/60vgs5ip6bp7az83z7yi3hkrpgjcp2qd-libidn2-2.3.4` appeared in the Nix store while building.
Error output:
```
CppStdException "path '/nix/store/60vgs5ip6bp7az83z7yi3hkrpgjcp2qd-libidn2-2.3.4' is not valid" (Just "nix::InvalidPath")
```
I guess this is partially caused by this [no-bootstrap-reference hack](https://github.com/NixOS/nixpkgs/blob/26937f95223cdd917418dfc4e9957a5f81f012f9/pkgs/stdenv/linux/default.nix#L663).

Originally, this happened while building `systemd 253` with Cachix on newer nixpkgs.

### Reproduce
https://github.com/erikarvstedt/cachix-bug-repro builds a drv with `cachix watch-exec`, triggering the bug.
The error is visible in the [CI build log](https://github.com/erikarvstedt/cachix-bug-repro/runs/14534724721).

### Affected Cachix versions
Probably all recent versions (I've checked 1.1, 1.2, 1.3.3, 1.5).
In versions <=  1.2, Cachix exits, but the Nix build command keeps running, with output attached to TTY.

**Comment by domenkozar** [comment]
Could you try using Cachix 1.5, which is in `nixos-23.05`?

**Comment by erikarvstedt** [comment]
Yes.
> I've checked (..., 1.5).

**Comment by erikarvstedt** [comment]
Already did that.
> I've checked (..., 1.5).

I've now switched the repro repo to 1.5 ([build log](https://api.cirrus-ci.com/v1/task/6297776070328320/logs/build.log)).

**Comment by domenkozar** [comment]
Could you switch the repro to 1.5? I can't reproduce it locally.

**Comment by erikarvstedt** [comment]
Already did that, as stated in my prev msg.

**Comment by domenkozar** [comment]
Do you have a log for it?

**Comment by erikarvstedt** [comment]
Yes, see the link `build log`.

**Comment by erikarvstedt** [comment]
If the repro doesn't work locally for you, check [this line in the repro script](https://github.com/erikarvstedt/cachix-bug-repro/blob/e5ee6516315fec45d989eb4784954c9095a9192f/build-with-cachix.sh#L16).

**Comment by domenkozar** [comment]
This is most likely an issue with `nixpkgs/nix-flakes:nixos-22.11` image: https://github.com/nix-community/docker-nixpkgs/issues/63

**Comment by erikarvstedt** [comment]
I can consistently repro this in a local VM.
I've added a VM-based repro to the repo: https://github.com/erikarvstedt/cachix-bug-repro/blob/master/vm-repro.sh
Run these lines manually in a shell.

**Comment by sandydoo** [comment]
Thanks for the VM repro, @erikarvstedt!

@domenkozar, I managed to repro this. The path causing the Nix error doesn't exist in the store. The lock file for it must have been created for us to pick it up, but it's unclear what happened to the actual store path...

> I guess this is partially caused by this [no-bootstrap-reference hack](https://github.com/NixOS/nixpkgs/blob/26937f95223cdd917418dfc4e9957a5f81f012f9/pkgs/stdenv/linux/default.nix#L663).

This is the likely culprit, particularly [this symlink](https://github.com/NixOS/nixpkgs/blob/2de8efefb6ce7f5e4e75bdf57376a96555986841/pkgs/development/libraries/libidn2/no-bootstrap-reference.nix#L28).

```
building of '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv!dev' from .drv file: woken up
building of '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv!dev' from .drv file: trying to build
locking path '/nix/store/myfx5rpir457vfgnq28cj3svdqkdnszd-libidn2-2.3.4-dev'
lock acquired on '/nix/store/myfx5rpir457vfgnq28cj3svdqkdnszd-libidn2-2.3.4-dev.lock'
locking path '/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4'
lock acquired on '/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4.lock'
locking path '/nix/store/zd4cl1r4cabmv7gg4qplbhx1g6s62m17-libidn2-2.3.4-bin'
lock acquired on '/nix/store/zd4cl1r4cabmv7gg4qplbhx1g6s62m17-libidn2-2.3.4-bin.lock'
skipping build of derivation '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv', someone beat us to it
building of '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv!dev' from .drv file: done
building of '/nix/store/r147ri48sjzmir311w8cxjgf1ifanmjb-repro.drv!out' from .drv file: waitee 'building of '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv!dev' from .drv file' done; 0 left
building of '/nix/store/r147ri48sjzmir311w8cxjgf1ifanmjb-repro.drv!out' from .drv file: woken up
lock released on '/nix/store/myfx5rpir457vfgnq28cj3svdqkdnszd-libidn2-2.3.4-dev.lock'
lock released on '/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4.lock'
lock released on '/nix/store/zd4cl1r4cabmv7gg4qplbhx1g6s62m17-libidn2-2.3.4-bin.lock'
building of '/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv!dev' from .drv file: goal destroyed
building of '/nix/store/r147ri48sjzmir311w8cxjgf1ifanmjb-repro.drv!out' from .drv file: all inputs realised
```

```
[nixos@nixos:~/cachix-bug-repro]$ ls /nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4
ls: cannot access '/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4': No such file or directory
```

`nix show-derivation /nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv`:
```
{
  "/nix/store/z7yarvk4a4v57356kx6pgplfs1s3g9bp-libidn2-2.3.4.drv": {
    "outputs": {
      "bin": {
        "path": "/nix/store/zd4cl1r4cabmv7gg4qplbhx1g6s62m17-libidn2-2.3.4-bin"
      },
      "dev": {
        "path": "/nix/store/myfx5rpir457vfgnq28cj3svdqkdnszd-libidn2-2.3.4-dev"
      },
      "out": {
        "path": "/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4"
      }
    },
    "inputSrcs": [
      "/nix/store/6xg259477c90a229xwmb53pdfkn6ig3g-default-builder.sh"
    ],
    "inputDrvs": {
      "/nix/store/33kmggkzsyagz47ffwqml5mm2zhmaiyp-bash-5.2-p15.drv": [
        "out"
      ],
      "/nix/store/8qkzdykr1ss6hpg9gh4wdyxgh3a2wnxh-stdenv-linux.drv": [
        "out"
      ],
      "/nix/store/akl3min1sm2pd3hxx58h7w0i08h2i5q9-libunistring-1.1.drv": [
        "out"
      ],
      "/nix/store/bg7dvbnwyf9r88lf0achly9634mxxzyi-glibc-2.37-8.drv": [
        "out"
      ],
      "/nix/store/d7xv2p8namvqlgybbyyy6lwmpp5w05wd-libidn2-2.3.4.drv": [
        "bin",
        "dev",
        "out"
      ]
    },
    "system": "aarch64-linux",
    "builder": "/nix/store/kbv664x6km2j3jpk12wxp040dqiv9821-bash-5.2-p15/bin/bash",
    "args": [
      "-e",
      "/nix/store/6xg259477c90a229xwmb53pdfkn6ig3g-default-builder.sh"
    ],
    "env": {
      "__structuredAttrs": "",
      "allowSubstitutes": "",
      "bin": "/nix/store/zd4cl1r4cabmv7gg4qplbhx1g6s62m17-libidn2-2.3.4-bin",
      "buildCommand": "cp -r '/nix/store/54wlspyia452b422azczai4pd2ykvwvq-libidn2-2.3.4-bin' \"$bin\"\nchmod +w \"$bin\"/bin/*\npatchelf \\\n  --set-interpreter '/nix/store/daa76x5m9fbwd6g35n2gbp699alivvd3-glibc-2.37-8/lib/ld-linux-aarch64.so.1' \\\n  --set-rpath '/nix/store/daa76x5m9fbwd6g35n2gbp699alivvd3-glibc-2.37-8/lib:/nix/store/f76qcfjfy3a852p29m4jqv2vasy3ivq1-libunistring-1.1/lib:/nix/store/cgpgvvwyqnmphcnjm6mhy37kylcw78dd-libidn2-2.3.4/lib' \\\n  \"$bin\"/bin/*\n\ncp -r '/nix/store/1kjajd7r9j5zp39bpayxz1xqnkqf1zaz-libidn2-2.3.4-dev' \"$dev\"\nchmod +w \"$dev\"/nix-support/propagated-build-inputs\nsubstituteInPlace \"$dev\"/nix-support/propagated-build-inputs \\\n  --replace '/nix/store/54wlspyia452b422azczai4pd2ykvwvq-libidn2-2.3.4-bin' \"$bin\"\nsubstituteInPlace \"$dev\"/lib/pkgconfig/libidn2.pc \\\n  --replace '/nix/store/1kjajd7r9j5zp39bpayxz1xqnkqf1zaz-libidn2-2.3.4-dev' \"$dev\"\n\nln -s '/nix/store/cgpgvvwyqnmphcnjm6mhy37kylcw78dd-libidn2-2.3.4' \"$out\" # it's hard to be without any $out\n",
      "buildInputs": "",
      "builder": "/nix/store/kbv664x6km2j3jpk12wxp040dqiv9821-bash-5.2-p15/bin/bash",
      "cmakeFlags": "",
      "configureFlags": "",
      "depsBuildBuild": "",
      "depsBuildBuildPropagated": "",
      "depsBuildTarget": "",
      "depsBuildTargetPropagated": "",
      "depsHostHost": "",
      "depsHostHostPropagated": "",
      "depsTargetTarget": "",
      "depsTargetTargetPropagated": "",
      "dev": "/nix/store/myfx5rpir457vfgnq28cj3svdqkdnszd-libidn2-2.3.4-dev",
      "doCheck": "",
      "doInstallCheck": "",
      "enableParallelBuilding": "1",
      "enableParallelChecking": "1",
      "enableParallelInstalling": "1",
      "mesonFlags": "",
      "name": "libidn2-2.3.4",
      "nativeBuildInputs": "",
      "out": "/nix/store/wjxr3yqc8wkl214039wnh979qq6npwmc-libidn2-2.3.4",
      "outputs": "bin dev out",
      "passAsFile": "buildCommand",
      "patches": "",
      "preferLocalBuild": "1",
      "propagatedBuildInputs": "",
      "propagatedNativeBuildInputs": "",
      "stdenv": "/nix/store/is7khx5p7nfij2wxg4hlkk7777zy5mfa-stdenv-linux",
      "strictDeps": "",
      "system": "aarch64-linux"
    }
  }
}
```

**Comment by sandydoo** [comment]
I've narrowed it down to the query loop, in particular this call to `computeFSClosure`. https://github.com/cachix/cachix/blob/b298fb341d2933d161641fe79b317d7a9bce5a08/cachix/src/Cachix/Client/Push.hs#L285

It seems like we're missing a `filterInvalidStorePaths` in the code path for `watch-exec`, which is how this path is getting through to this point. Filtering it out right before this call is enough to fix the error on our side.

The remaining question is whether this is something that should be raised upstream. As I understand it, this particular path should still exist and be a symlink to original.

**Comment by erikarvstedt** [comment]
Thanks!

@sandydoo, do you think this issue uncovered a Nix bug that should be filed upstream?

**Comment by sandydoo** [comment]
> Thanks!
> 
> 
> 
> @sandydoo, do you think this issue uncovered a Nix bug that should be filed upstream?

Yeah, possibly. I'd like to open an issue to get some feedback on whether this is intended behavior or not. I won't have time today, so you're very welcome to do so if you're inclined 🙂

**Comment by sandydoo** [comment]
I ran the libidn2 repro against the latest stable nixpkgs and I can't reproduce the missing out path issue anymore.
