### ISSUE TITLE
xz compression caps upload at ~3-5mbit/s

### ISSUE THREAD

**Issue by nh2** [cachix/cachix#55]
`cachix push` is uploading with 3-5 Mbit's from my 1000 Mbit/s connection from Zurich.

I suspect the biggest reason is lack of HTTP keepalive; every upload is a new HTTP(s!) / TCP connection. That resets the TCP window size for every package.

I think that if you move this code that creates the HTTP manager

https://github.com/cachix/cachix/blob/fed0a719e4c63a693b6a593004b7a6e7e92216e8/cachix/src/Cachix/Client/Commands.hs#L235-L237

out of the `go` loop, it will use keepalive across all packages, one TCP connection, and be a lot faster.

---

Further consider to enable BBR congestion control on the server side. For my servers it has a huge impact and allows me to push 1 Gbit/s over oceans without problems.

```nix
{
    boot.kernelModules = [ "tcp_bbr" ];

    # Enable BBR congestion control
    boot.kernel.sysctl."net.ipv4.tcp_congestion_control" = "bbr";
    boot.kernel.sysctl."net.core.default_qdisc" = "fq"; # see https://news.ycombinator.com/item?id=14814530
}
```

**Comment by danbst** [comment]
This may be also a throttling from server side

**Comment by nh2** [comment]
I thought up some garbage here, sorry. Of course updating the pure `baseUrl` inside `env` has no effect on the `Manager` contained within `env`. Sorry for the confusion. The issue must be somewhere else.

**Comment by nh2** [comment]
There is definitely something funny going on. Even changing from `mapPool 4` to `mapPool 400` doesn't change the throughput. But at closer look, `cachix` is CPU-bound. It must be doing something expensive somewhere.

**Comment by domenkozar** [comment]
I'd say it's lzma compression with level 6.

**Comment by domenkozar** [comment]
https://goo.gl/images/MHFiHN

**Comment by nh2** [comment]
> I'd say it's lzma compression with level 6.

Oh yeah that makes sense. Are other compressions also supported? With LZMA it will be impossible to reach gigabit line speed.

**Comment by nh2** [comment]
Indeed switching from `.| compress Nothing` to `.| compress (Just 0)` brings me up to ~50 Mbit/s. Better, but still factor 20 below nice working conditions.

Are there other crompression methods available?

For example, `gzip -1` can do 25 MB/s per core, `lzop` can do 400 MB/s per core.

**Comment by domenkozar** [comment]
We could also support gzip, but I'd leave xz as default since there's the tradeoff between CPU or Network (+ size of transfer).

Maybe we should opt-in for compression level 4 or 5.

**Comment by domenkozar** [comment]
@nh2 would gzip solve your concern (trade CPU for size)?

**Comment by domenkozar** [comment]
@nh2 took the liberty to rename the title, if you think gzip would help I'm happy to consider implementing this as a flag :)

**Comment by nh2** [comment]
@domenkozar Yeah I think it would be great if we could have gzip vs xs and the level user-configurable.

Because as mentioned above, with `gzip -1` you can do 25 MB/s per core, so 4 cores can saturate a Gigabit uplink.

I think it's good to have this as an option because the optimal value depends a lot on how the user wants to use cachix:

* If they want to upload to cachix to simplify and speed up deployments to mainly their own infrastructure with great Internet connection, then latency is key and size doesn't matter, so getting a 100x speedup from `gzip -1` over `xz` would benefit them greatly.
* If they want to upload to cachix to make a long-running cache.nixos.org alternative targeted at NixOS main users (of which there may be many and they may download occasionally, perhaps with ADSL connections), then small size is key and the initial upload being 100x longer may be worth it for them.

**Comment by nh2** [comment]
@domenkozar Another question (not important now, but perhaps interesting for later): Does nix allow only downloads in `xz` and `gzip`, or can it also support other algorithms?

For example, [`zstd`](https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/) seems like a very good tradeoff for software packages.

**Comment by edolstra** [comment]
Note that in my experience, zstd and brotli don't compress binaries better than xz.

Nix does already support brotli compression (e.g. `nix copy --to file:///bla?compression=br`). Unfortunately, the default compression quality (11) makes it superslow, about 10x slower than xz -6 (with a worse compression ratio). OTOH with quality 6 it's 6x faster than xz -6. So we really should have a setting in Nix for the compression quality.

**Comment by nh2** [comment]
> Note that in my experience, zstd and brotli don't compress binaries better than xz.

@edolstra That's correct, `xz` remains to have the best compression ratio (this is also stated in the [article](https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/) I linked). The idea is that it compresses a lot _faster_.

Here are some examples:

```
zstd v1.3.4
brotli 1.0.4
xz 5.1.0alpha
gzip 1.6
lzop 1.03, LZO library 2.08
```

```
% du -sh /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/
310M  /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | lzop | pv > /dev/null
 140MiB 0:00:01 [ 130MiB/s]

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | gzip | pv > /dev/null
98.2MiB 0:00:11 [8.85MiB/s]

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | zstd | pv > /dev/null
94.5MiB 0:00:01 [60.8MiB/s]

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | xz | pv > /dev/null
66.6MiB 0:02:10 [ 524KiB/s]

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | brotli --quality=6 - | pv > /dev/null
79.6MiB 0:00:13 [5.77MiB/s]

% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | brotli --quality=3 - | pv > /dev/null
  93MiB 0:00:02 [  31MiB/s]
```

`zstd` is

* 7x faster than `gzip` while having the same output size
* 120x faster than `xz` while having 30% increased output size
* 2x faster than `brotli --quality=4` while having the same output size

It also supports mutliple cores; when used, that bumps the above numbers by some more integer factors:

```
% tar c /nix/store/cn8yyi1z0y79hjnvs7qpmrb23drphhb6-chromium-65.0.3325.162/ | zstd -T4 | pv > /dev/null
94.5MiB 0:00:00 [ 140MiB/s]
```

But let us move the discussion for the nix side to https://github.com/NixOS/nix/issues/2255, and leave this issue for the cachix bits.

**Comment by domenkozar** [comment]
Cachix controls the compression level, so using `brotli --quality 4` would work instead of gzip, but I need to compare size ratios and compression+decompression speeds.

**Comment by dtzWill** [comment]
If there is still interest in nix-level support I can revive the PR's
for adding zstd support and for setting compression level via store URI.

They worked well AFAIK but as I recall need some minor reworking to be
compatible with latest Nix.  That said they're nothing magical so
tackling them fresh might be the same amount of effort :).

~Will

**Comment by domenkozar** [comment]
@nh2 something we can easily support today is xz compression level.

```
$ tar c /nix/store/zdmjdaqznr3n9xyq1mcrip7kz6wxrm3k-ghc-8.4.3 | xz -0 | pv > /dev/null                          
 137MiB 0:00:34 [3.95MiB/s] [                                                                 <=>                            ]

$ tar c /nix/store/zdmjdaqznr3n9xyq1mcrip7kz6wxrm3k-ghc-8.4.3 | xz | pv > /dev/null                             
 100MiB 0:07:25 [ 231KiB/s] [                                                                                     <=>        ]
```

So instead of uploading ghc in 7.5min, it would take 30s. In the future, cachix could recompress those files to save storage. What do you think, would adding `cachix push --compression-level` help?

**Comment by danbst** [comment]
`zstd -7` is faster and produces smaller result than `xz -0`
```
➜ tar -c /nix/store/1d9vjks0m4kqmas176r12cczz29ym1mv-clang-7.0.1 | zstd -7 | pv > /dev/null                                                                         
 136MiB 0:00:16 [8.52MiB/s] 

➜ tar -c /nix/store/1d9vjks0m4kqmas176r12cczz29ym1mv-clang-7.0.1 | xz -0 | pv > /dev/null                                                                          
 139MiB 0:00:35 [3.95MiB/s]
```
On decompression `zstd` heats CPU much less than `xz`:
```
➜ cat /dev/shm/archive.zstd | zstd -d | pv >/dev/null
 609MiB 0:00:01 [ 519MiB/s]

➜ cat /dev/shm/archive.xz | xz -d | pv >/dev/null
 609MiB 0:00:12 [47.2MiB/s]
```

**Comment by domenkozar** [comment]
@danbst to be clear, I'm not saying zstd is not superior, but we could have xz compression level tomorrow, while zstd support will take more time.

**Comment by nh2** [comment]
@domenkozar Yes, compression level on the command line would be a good first mitigation, for tomorrow, definitely helpful until faster methods can be done later.

**Comment by domenkozar** [comment]
According to https://community.centminmod.com/threads/round-3-compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.17259/ it seems brotli vs xz doesn't make a huge difference, but adding zstd support would.

**Comment by nh2** [comment]
> it seems brotli vs xz doesn't make a huge difference

@domenkozar My reading of the tables doesn't confirm that:

![image](https://user-images.githubusercontent.com/399535/60595079-96b3ab80-9da6-11e9-9cfb-f5ac3a07a96f.png)

![image](https://user-images.githubusercontent.com/399535/60595127-afbc5c80-9da6-11e9-89a3-044ffab3e6af.png)

`brotli` can compress at close-to Gigabit Ethernet line rate (~80 MB/s), `xz` cannot (17 MB/s).

That is a practical ~5x difference when uploading.

**Comment by domenkozar** [comment]
I also need to evaluate compression ratio, as otherwise people will complain about the storage size.

Practically speaking 10MB/s seems like a good balance, anything beyond that should be configurable but not the default.

**Comment by nh2** [comment]
@domenkozar That makes sense; what I meant to point out is that the difference between brotli and xz is that brotli can be configured to be fast, while xz cannot. That's what makes me think that when choosing between xz and brotli, brotli looks like a better stopgap solution.

zstd certainly solves it fullly because of its wide range of speed-vs-size control options.

**Comment by domenkozar** [comment]
Once I add support for another compression, adding the third is really easy.

Meanwhile I propose setting xz level to 2 as default but make it overridable if someone wants to save on storage.

**Comment by nh2** [comment]
@domenkozar That seems fine to me -- I don't really mind what the default is as long as flags are available so that users can adjust. Though the new default you propose that'd be ~10 MB/s would already be a lot better than the current speed from the issue description.

**Comment by domenkozar** [comment]
See #200 for short term fix. Needs benchmarking.

Further optimizations:
- [ ] support brotli/zstd compression
- [ ] recompress archives to xz with high compression level

**Comment by domenkozar** [comment]
This was fixed mid-term as you can tinker with xz compression level now, for long term see https://github.com/cachix/cachix/issues/205
