### ISSUE TITLE
On single-user installations, provide a good error when invoking cachix with root

### ISSUE THREAD

**Issue by nh2** [cachix/cachix#56]
`nix` wants to be installed as non-root on non-NixOS.

Then I do that, and `cachix use` gets me:

```
$ cachix use static-haskell-nix
Configured https://static-haskell-nix.cachix.org binary cache in /home/niklas/.config/nix/nix.conf
Warning: Couldn't create /etc/nix :/etc/nix: createDirectory: permission denied (Permission denied)Warning: Couldn't create /etc/nix :/etc/nix: createDirectory: permission denied (Permission denied)
```

then as root:

```
# cachix use static-haskell-nix
cachix: command not found
```

```
# /home/niklas/.nix-profile/bin/cachix use static-haskell-nix
nix-env: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

```
# . /home/niklas/.nix-profile/etc/profile.d/nix.sh
Nix: WARNING: bad ownership on /nix/var/nix/profiles/per-user/root, should be 0
Nix: WARNING: bad ownership on /nix/var/nix/gcroots/per-user/root, should be 0
```

No easy time yet!

**Comment by domenkozar** [comment]
You have to use it as non-root all the way since Nix is not installed for root user.

But there are a few things that can be done:

a) error out if `nix-env` is not available with a clear message
b) cachix would fail using root user on single-user installations and tell what to do

That's whay I can think of :)

**Comment by nh2** [comment]
> You have to use it as non-root all the way since Nix is not installed for root user.

I see. Indeed the error disappears works fine when I move `/etc/nix/nix.conf` to `/home/niklas/.config/nix/nix.conf`.

However, by now I'm glad it didn't work the first time:

`cachix use` seems to _override_ the file entierly, throwing away any settings I had in there. Is that intended?

> But there are a few things that can be done:
> 
> a) error out if nix-env is not available with a clear message
> b) cachix would fail using root user on single-user installations and tell what to do

These sound good.

**Comment by domenkozar** [comment]
@nh2 could you copy the file you had?

**Comment by nh2** [comment]
```
% cat /home/niklas/.config/nix/nix.conf
build-max-jobs = 8
trusted-substituters = ssh://nix-store-user@myhost.example.com
trusted-public-keys = myhost.example.com-1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
require-sigs = false
binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org https://cache.allvm.org
binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= gravity.cs.illinois.edu-1:yymmNS/WMf0iTj2NnD0nrVV8cBOXM9ivAkEdO1Lro3U=
binary-caches-parallel-connections = 40
```

**Comment by domenkozar** [comment]
:hankey:

**Comment by domenkozar** [comment]
Found the issue, `NixConf.read` signals `Nothing` for unfound file and also parsing error, so your config fails to parse and Cachix thinks it's empty. Need to make this explicit and fix the parsing issue :)

**Comment by domenkozar** [comment]
@nh2 thanks for playing :) https://github.com/cachix/cachix/pull/76

**Comment by nh2** [comment]
@domenkozar Great, with that PR cachix no longer deletes my nix settings and adds itself correctly.

Only remaining weirdness:

* cachix reorders the lines in `nix.conf` when writing the file out (I don't know if order of lines matters in `nix.conf`)
* it does so in _reverse_ lexicographical order (that sounds like some cons (`:`) based parsing without final `reverse`)

**Comment by domenkozar** [comment]
Not quite, it keeps the order but appends configured lines at the end (substitutes, public keys). This is due to the logic [here](https://github.com/cachix/cachix/blob/master/cachix/src/Cachix/Client/NixConf.hs#L60-L63) where it covers the use case of existing line or if it has to append one.

**Comment by nh2** [comment]
Ah I see, you are right.

**Comment by domenkozar** [comment]
for b) cachix could use test at https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/nix/info/multiuser.nix to see if Nix should even work.

**Comment by domenkozar** [comment]
Yeah, the warning is confusing, it should at the very least come in opposite order :)

**Comment by domenkozar** [comment]
BTW, warning should have been fixed in https://github.com/cachix/cachix/commit/cefc4df86ac256a8141ec35d5212c627f063e14c

**Comment by domenkozar** [comment]
All of the problems have been addressed here, except if you don't install cachix as root - not sure how to fix that.
