### ISSUE TITLE
Search grayed out

### ISSUE THREAD

**Issue by Radvendii** [cachix/cachix#569]
I'm not sure what it means, but on every cachix page I look, the search tab is grayed out and un-clickable.

tested with: tweag-nickel.cachix.org, lean4.cachix.org, cachix.cachix.org

![2023-08-14-081643_1043x105_scrot](https://github.com/cachix/cachix/assets/1239929/b4cc7179-1282-4845-96fe-cfd73ea032b8)

**Comment by domenkozar** [comment]
Currently only the admins are allowed to search. 

If you're the owner the caches, would you like anyone to search the contents?

**Comment by Radvendii** [comment]
Anyways, I'll close this since I understand what's going on and that is a separate issue. Let me know if you'd like me to make another issue for it.
