### ISSUE TITLE
Correct way to install cachix?

### ISSUE THREAD

**Issue by mtlynch** [cachix/cachix#580]
The Cachix web app and the Cachix docs give different instructions for installing Cachix.

In the Cachix web app:

>`nix-env -iA cachix -f https://cachix.org/api/v1/install`

![image](https://github.com/cachix/cachix/assets/7783288/7bcd4462-e472-4160-af96-0936c149192b)

In the Cachix docs:

>`nix-env -iA nixpkgs.cachix nixpkgs.bash`

https://docs.cachix.org/continuous-integration-setup/circleci

Which is correct?

**Comment by domenkozar** [comment]
Both are fine, you'll get the latest version.
