### ISSUE TITLE
Multi-threaded push exits with `SIGPIPE`/exit code 141 (workaround)

### ISSUE THREAD

**Issue by donn** [cachix/cachix#594]
Just documenting this for posterity:

Attempting to push a lot of (larger) packages on macOS results in the following output:

```
Pushing 9 paths (282 are already present) using zstd to cache openlane ⏳

✓ /nix/store/zfnc6mbakfrh7nlri48i3x7yxgj2d3ql-yosys-abc (11.59 MiB)
✓ /nix/store/4piwr69l9sqg8wz7fx1aacqgvmz593ar-klayout (74.22 MiB)
✓ /nix/store/i37wvd5m5qx3my609f9vrxil112y7id8-yosys (19.90 MiB)
✓ /nix/store/1mvr8kxsh2g6p0l3a4hkwy1xb0lzna05-yosys-synlig-sv (15.12 MiB)
✓ /nix/store/7qphk2lf4xyhkgi7c5wyvwcrh0s677gj-surelog-1.76 (89.70 MiB)
✓ /nix/store/vslnbaiy5j8x8wc8h0xn8hz7vsdbjxp3-or-tools-9.4 (21.68 MiB)
✓ /nix/store/d2cbzkgqwfqijawnzrclmcp4krjpnbwy-openroad (70.70 MiB)
✓ /nix/store/7qfb1nza23nwz30jny869smx67ji503i-verilator (171.78 MiB)
```

Then a short hang, followed by an exit with code 141, i.e. `SIGPIPE`. None of the paths shown were ultimately uploaded to Cachix.

This could be any of my internet connection, macOS, or an unknown cachix bug. At any rate, passing `-j1` to cachix works around this issue.

(Thank you @domenkozar for the help over chat.)

---
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by sandydoo** [comment]
What we can do is remove the default sigPIPE handler and just ignore it. Whatever socket is failing should then throw an error that we can inspect.

**Comment by domenkozar** [comment]
This should be fixed on master
