### ISSUE TITLE
`cachix deploy activate` works without authentication

### ISSUE THREAD

**Issue by philon123** [cachix/cachix#614]
When I run the command without any CACHIX_AUTH_TOKEN, it will activate the spec despite me being unauthenticated. 

`cachix push ..` gives me the expected output however: 
```
Neither auth token nor signing key are present.

They are looked up via $CACHIX_AUTH_TOKEN and $CACHIX_SIGNING_KEY,
and if missing also looked up from ~/.config/cachix/cachix.dhall

Read https://mycache.cachix.org for instructions how to push to your binary cache.
```

I hope this is not expected behavior because we dn't want to allow anyway to run deployments on our servers :)

**Comment by sandydoo** [comment]
Deploy activation currently uses a separate `CACHIX_ACTIVATE_TOKEN`. Perhaps it was already set?

**Comment by domenkozar** [comment]
We extract the workspace id from the token itself so it's not possible you can activate without a token :)
