### ISSUE TITLE
cachix: thread blocked indefinitely in an STM transaction

### ISSUE THREAD

**Issue by srid** [cachix/cachix#631]
I saw this error appear in the first CI run here,

https://github.com/juspay/services-flake/pull/127#issuecomment-1983798627

- CI: https://github.com/juspay/services-flake/pull/127#issuecomment-1983798627
- Commit: https://github.com/juspay/services-flake/pull/127/commits/24a02bf7caf2526349c313113cb90e95fc387360

Let me know if I can provide any more information.

**Comment by domenkozar** [comment]
Could you try with our master branch?

**Comment by srid** [comment]
Will do, the next time it occurs.

**Comment by srid** [comment]
Probably won't be spending time on this; planning to switch over to `attic`.
