### ISSUE TITLE
cli fails with lix

### ISSUE THREAD

**Issue by KiaraGrouwstra** [cachix/cachix#644]
**Describe the bug**

using lix cachix seems to error out:

- [use lix](https://lix.systems/add-to-config/#flake-based-configurations)
- try a cachix command: `nix run nixpkgs#cachix -- use kiara`
- find error: `Couldn't parse 'nix-env --version' output: nix-env (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`

**Version**
 
Paste the output of `$ cachix --version`

1.7

**Comment by lf-** [comment]
sigh, we put the `like Nix` thing in because old `nix upgrade-nix` was doing busted parsing of the nix --version output. it seems like no matter what we do someone will do busted parsing of our version output, huh.

**Comment by sandydoo** [comment]
Thank, will get this fixed 🙂
