### ISSUE TITLE
`cachix daemon stop` should exit nonzero if any queued paths failed to push

### ISSUE THREAD

**Issue by cmoog** [cachix/cachix#654]
**Describe the bug**

I want to run `cachix daemon stop` and be sure that upon its completion, all queued store paths were successfully pushed. I've noticed that although it awaits for all queued pushes to "complete", if those pushes complete with an error, `daemon stop` still exits successfully. 

**Version**
 
```
cachix 1.7.3
```

**Comment by sandydoo** [comment]
Added in https://github.com/cachix/cachix/pull/660

**Comment by sandydoo** [comment]
Added in https://github.com/cachix/cachix/pull/660
