### ISSUE TITLE
NAR hash mismatch

### ISSUE THREAD

**Issue by Enzime** [cachix/cachix#664]
**Describe the bug**

```
/nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5: the computed NAR hash doesn't match the hash returned by the Nix store.

Expected: sha256:12wh4f4zzkvv7b3z9v5z1aihszcbr02v600js5xb0fg02m8q1vhn
Got:      sha256:1cccbw37q5v8ydmm0bl24f0gb10h7qrh3sf755anp9bhjj585gpi
```

This store path can be built on an `aarch64-darwin` machine at:

```
$ nix build nixpkgs/d603719ec6e294f034936c0d0dc06f689d91b6c3#iina
$ realpath ./result
/nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5
```

**Version**
 
Running latest master with `hnix-store-core` 0.7.0.0

**Comment by sandydoo** [comment]
@Enzime, could you please share the `nix-store --dump` for this path?

**Comment by sandydoo** [comment]
Oh, sorry, just noticed the nixpkgs commit hash. Will look into this!

**Comment by sandydoo** [comment]
@Enzime, I wrote up a fix for this here: https://github.com/haskell-nix/hnix-store/pull/282

Some of the localisation resources are marked as executable, but `access` with `X_OK` returns false for them.
Do you have any idea why this would be the case?

I've tried creating a file with similar permissions, ownership, and extension; adding it to the store, dumping, and restoring it. I just can't replicate this manually. Maybe there's more to this story.

**Comment by sandydoo** [comment]
`result/Applications/IINA.app/Contents/Resources/de.lproj/AboutWindowController.strings` is one such example. It's the first point of failure in the NAR.

If this file is `cp`'d from the nix store, `access` returns true.
If the whole output is `cp -r`'d, then `access` returns false.

**Comment by Enzime** [comment]
I can reproduce the same thing, I can't figure out what would cause this...

`xattr -lv` returns no extended attributes for both
`ls -lO` shows neither of them have any flags on them

**Comment by Enzime** [comment]
Maybe calling `getattrlist(2)` on both files and comparing that might show the difference?

https://keith.github.io/xcode-man-pages/getattrlist.2.html

**Comment by Enzime** [comment]
Actually, I don't think I can reproduce what you're seeing

```
$ [[ -x /nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5/Applications/IINA.app/Contents/Resources/de.lproj/AboutWindowController.strings ]] && echo "executable"
$ cp -r /nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5/Applications/IINA.app/Contents/Resources/de.lproj/ de.lproj
$ [[ -x de.lproj/AboutWindowController.strings ]] && echo "executable"
executable
```

**Comment by Enzime** [comment]
I think I've figured it out, any file inside a `.lproj` inside a macOS app will not be considered as executable (`*.app/**/Resources/*.lproj/*`)

```
$ mkdir -p temp/test.app/Argh/Yabba/Resources/you-know-it.lproj
$ cp /bin/bash temp/test.app/Argh/Yabba/Resources/you-know-it.lproj
$ [[ -x temp/test.app/Argh/Yabba/Resources/you-know-it.lproj/bash ]] && echo "exec" || echo "not exec"
not exec
$ ./temp/test.app/Argh/Yabba/Resources/you-know-it.lproj/bash
zsh: operation not permitted: ./temp/test.app/Argh/Yabba/Resources/you-know-it.lproj/bash
$ mv temp/test.app/Argh/Yabba/Resources/you-know-it.lproj/bash temp/test.app/Argh/Yabba/Resources/
$ [[ -x temp/test.app/Argh/Yabba/Resources/bash ]] && echo "exec" || echo "not exec"
exec
```

**Comment by sandydoo** [comment]
> I think I've figured it out, any file inside a .lproj inside a macOS app will not be considered as executable (*.app/**/Resources/*.lproj/*)

Oh, wow, so it is path-dependent. Thanks! We've got a working test-case now: https://github.com/haskell-nix/hnix-store/pull/282/commits/c0ff55d9e4a7772ea99d91cc826241f443a716f9#diff-c530f553a5477e3589712944a1a56beaa414abfa41393a9d4105a1b7595025fdR148-R152
