### ISSUE TITLE
cachix claims "all done" when echo'ing multiple paths on same line?

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#69]
Somewhere I think I saw a suggestion that `echo /nix/store//path | cachix push $MYCACHIX`, which I've been using for items I've already built or when the store path is more handy than the original derivation (which I have too but may be in a different machine's shell history :P or something).

Anyway, when I wanted to upload two paths I tried this:

```console
$ echo /nix/store/zzcy2xwz618jw9ggfqqsj4vn5xjggaxb-aarch64-unknown-linux-musl-ghc-8.2.2 /nix/store/ziacs8l9ny5ag5dxw8zm48xwm1is57fi-hello-1.0.0.2-aarch64-unknown-linux-musl|cachix push allvm
All done.
```

Which appears to not be recognized as two paths but zero paths?

Not sure if this is expected, but thought I'd report/ask to double-check :).

On the same subject-- when piping a nix-build to cachix (as some examples suggest I believe) what sort of paths are pushed? Anything matching some pattern? Any path printed by itself on a single line? Thanks! :)

**Comment by dtzWill** [comment]
Well on the plus side it looks like I can easily pass multiple paths as arguments instead, woohoo! :)

**Comment by domenkozar** [comment]
Your example should definitely work. Cachix expects space separate paths on stdin or command line arguments. Are you saying that https://allvm.cachix.org/zzcy2xwz618jw9ggfqqsj4vn5xjggaxb.narinfo was then indexed by cli argument but did not work using echo?

About piping: `nix-build` will output all built derivations that were result of `default.nix` to stdout and all build output to stderr.

**Comment by domenkozar** [comment]
I'm lying, there's a bug: `T.lines <$> getContents`. So it will expect newline separated paths, I should fix this.

**Comment by domenkozar** [comment]
@dtzWill thanks - should be addressed by https://github.com/cachix/cachix/pull/72 - you can try it out as per description.
