### ISSUE TITLE
File containing secret key is world-readable

### ISSUE THREAD

**Issue by chris-martin** [cachix/cachix#70]
Cachix creates `~/.config/cachix/cachix.dhall` with permissions 644 - I think that ought to be locked down more so that the secret key isn't world-readable.

Also maybe `cachix authtoken` should prompt for the secret key instead of accepting it as a command-line argument? I imagine most users aren't going to think to disable their shell history when following the getting-started instructions.

**Comment by domenkozar** [comment]
@chris-martin yeah I'll fix this one for 0.1 :)

About separate file: could you open another issue?

**Comment by domenkozar** [comment]
https://github.com/cachix/cachix/pull/73

**Comment by chris-martin** [comment]
Opened the other issue - #74
