### ISSUE TITLE
FatalError {fatalErrorMessage = "You need to: export CACHIX_SIGNING_KEY=XXX"}

### ISSUE THREAD

**Issue by chris-martin** [cachix/cachix#71]
This is what happens when I try to push:

```
echo /nix/store/m46qjsrf6q0y7sqx8cp99mc556xl3wxb-nixos-system-monadic-party-18.03pre-git | cachix push chris-martin
pushing /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131pushing /nix/store/069g827lh3hrhp4vkcq3rsh5jh65pm3l-ncurses-6.0-20171125

pushing /nix/store/lird33c2j4mr289q1q17qihqhwq188wh-acl-2.2.52pushing /nix/store/cb3slv3szhp46xkrczqw7mscy5mnk64l-coreutils-8.29


FatalError {fatalErrorMessage = "You need to: export CACHIX_SIGNING_KEY=XXX"}
```

Is `CACHIX_SIGNING_KEY` something I should need to set manually?

**Comment by chris-martin** [comment]
How do I get the signing key if the config from the first machine is gone?

**Comment by domenkozar** [comment]
If you haven't written it down it's gone. Write to domen@enlambda.com and I'll help you create a new one :)

**Comment by chris-martin** [comment]
That was hypothetical :)

Maybe step 3 of the instructions should emphasize that you need to back up that key.

**Comment by domenkozar** [comment]
There's a separate step now to generate a key and it looks like this:

```
$ ./scripts/cachix staging generate-keypair foo
Signing key has been saved on your local machine. To populate
your binary cache:

    $ nix-build | cachix push foo

Or if you'd like to use the signing key on another machine or CI:

    $ export CACHIX_SIGNING_KEY=...
    $ nix-build | cachix push foo

To instruct Nix to use the binary cache:

    $ cachix use foo

IMPORTANT: Make sure to make a backup for the signing key above, as you have the only copy.
```

@chris-martin does this suffice?

**Comment by chris-martin** [comment]
Yay explanation!

I have one more thought - So it says:

> Signing key has been saved on your local machine.

Could it say *where* it has been saved? One appreciates being well-informed about which of one's files are being modified.

**Comment by domenkozar** [comment]
Actually, it does say that a line above (and it always has), but I've removed it from the example. 

Going to reword that a bit to say `Secret signing key has been saved in the file above.`. Thanks!
