### ISSUE TITLE
Retry transient HTTP errors

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#77]
Looks like some transient error--perhaps if this is common/expected cachix can automatically handle retrying internally? Dunno.

```
FatalError {fatalErrorMessage = "FailureResponse (Response {responseStatusCode = Status {statusCode = 500, statusMessage = \"Internal Server Error\"}, responseHeaders = fromList [(\"Server\",\"nginx\"),(\"Date\",\"Tue, 26 Jun 2018 19:45:20 GMT\"),(\"Content-Type\",\"text/plain; charset=utf-8\"),(\"Transfer-Encoding\",\"chunked\"),(\"Connection\",\"keep-alive\")], responseHttpVersion = HTTP/1.1, responseBody = \"Something went wrong\"})"}
```

store path of cachix used, FWIW: `/nix/store/f1h61j4b01ya3rqpqrmh2z6m4haf0rak-cachix-0.1.0.0/bin/cachix` (which is valiid path on `https://cachix.cachix.org`)

**Comment by domenkozar** [comment]
Seems to be a transient 500 from S3 service at `Jun 26 19:45:20` UTC.

Yeah, cachix server and client should support retries for GET requests.

**Comment by domenkozar** [comment]
@dtzWill I renamed the title to reflect what needs to be done rather the specific issue, hope you don't mind.
