### ISSUE TITLE
[feature request] upload derivation's references, all outputs?

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#78]
I'm finding myself often sending paths through something like:

```
$ nix-store -qR --include-outputs $(nix-store -q --deriver $PATHS_GO_HERE) | cachix push $SUBDOMAIN
```

I was wondering if this is something cachix maybe could do--but am unsure if it "should" and don't mean to distract from cachix's simple usage (strength) by suggesting adding flags for all the things :innocent: .

This pattern is useful to ensure everything needed to re-build the path is cached, which is also useful given the behavior of nix-shell pulling in all outputs of dependencies.  But also to ensure --for example-- debug info for dependencies is available even if it's not part of the final closure (intentionally).

On the other hand, this might be overkill for some scenarios, although I'm not sure what those are or how much people would care.

What do you folks think?

**Comment by domenkozar** [comment]
Duplicates https://github.com/cachix/cachix/issues/9
