### ISSUE TITLE
idea: operate as nix plugin?

### ISSUE THREAD

**Issue by dtzWill** [cachix/cachix#83]
I often find myself wanting to use cachix in a way more closely integrated with 'nix'.  Perhaps it would be beneficial/useful to explore providing a cachix Nix plugin to accomplish this?

Misc examples/ideas:

* use nix.conf for settings ? But then it's not dhall :(.
* use Nix's 2.0 "progress bar" prettiness
* interop with nix commands such as `nix copy` (maybe a cachix URI, so: `nix copy bash --to cachix://mine`)
  * currently you can point Nix to cachix caches with `--store https:/mine.cachix.org` but that's read-only :))
* maybe various tasks will be simpler / less duplication (not sure what is delegated to Nix currently, so might not be anything to improve here)

Not sure what exactly the Nix plugin API makes possible, but defining a new store type and misc options doesn't seem entirely out of scope ;).

**Comment by domenkozar** [comment]
Hey @dtzWill :)

1) Given I've written a parser for nix.conf I really dislike how simple yet fragile custom configuration file is, I'd prefer configuration to be typed with Dhall :)
2) There's #3 to implement that, I think Nix progress bar is too terse (ironically given to output Nix 1.0 had), so we'll see if we can come up with something in the middle
3) to support `nix copy` I just need to write a parser for `narinfo` files and it should be trivial to use nix to upload to Cachix without plugins - planned to do very soon :)

I see (2) as potentially only reason to do that, but I'd like exhaust options first to see if it's easy to do in Haskell as well :)

**Comment by dtzWill** [comment]
Thanks for the quick response! Haha sounds like there's not much to be done here, thanks for considering the idea!
