### ISSUE TITLE
Improve experience on NixOS

### ISSUE THREAD

**Issue by Infinisil** [cachix/cachix#91]
Currently running `cachix use` on NixOS causes it to output a message like this:
```nix
nix = {
  binaryCaches = [
    "https://cachix.cachix.org"
  ];
  binaryCachePublicKeys = [
    "cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM="
  ];
  trustedUsers = [ "root" "infinisil" ];
};
NixOSInstructions "Add above lines to your NixOS configuration file"
```

Which isn't very nice, especially since you can't just copy paste it into your configuration.nix when you have some caches already.

My suggestion: Cachix should store each cache you `use`, and regenerate a NixOS module (e.g. in `.cache/cachix/module.nix` each time consisting of `nix.{binaryCaches,binaryCachePublicKeys,trustedUsers}`. Then this can easily be included in NixOS.

The workflow would then be like this on NixOS:
0. (only first time) Add `~/.cache/cachix/module.nix` to your `configuration.nix` imports
1. `cachix use`
2. `nixos-rebuild switch`

instead of the current
1. `cachix use`
2. Copy output
3. Paste output while adjusting everything to fit into your `configuration.nix`
4. `nixos-rebuild switch`

(Yes it's possible to pipe the output of `cachix use` into a new nixos module file, and do some `readDir` logic to include all of them, but that's not very nice).

**Comment by domenkozar** [comment]
Could use [!include](https://nixos.org/nix/manual/#description-41) setting and just separate file for all caches

**Comment by domenkozar** [comment]
@Infinisil what if cachix wrote `/etc/nixos/cachix.nix` which would use `readDir` to load from `/etc/nixos/cachix/<name>.nix`?

**Comment by FRidh** [comment]
Why not have the module point to a (default) JSON file (`cachixUseCaches = "use.json";`) which `cachix use` can easily manipulate.

**Comment by domenkozar** [comment]
What's the benefit? :) I requires mutable operations on json, I'd like to avoid that unless there's a compelling reason.

**Comment by Infinisil** [comment]
@domenkozar While having a single module sounds better, in order to not store state I wouldn't mind the readDir version.

**Comment by Infinisil** [comment]
Can also super easily remove caches again with that

**Comment by domenkozar** [comment]
How about this:

```
$ sudo cachix use foobar
Cachix configuration written to /etc/nixos/cachix.nix.
Binary cache foobar configuration written to /etc/nixos/cachix/foobar.nix.

To start using cachix add the following to your /etc/nixos/configuration.nix:

    imports = [ ./cachix.nix ];

Then run:

    $ nixos-rebuild switch

```

**Comment by Infinisil** [comment]
Sounds good! One thing you should implement though is some way to customize the directory it uses. I personally (and probably lots of other people) don't use /etc/nixos for their NixOS config. An environment variable would probably be good.

**Comment by domenkozar** [comment]
Sure. Almost done :)

**Comment by domenkozar** [comment]
Will be part of #168
